USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_R22_CERIS_FILE_STG1]    Script Date: 04/07/2017 12:43:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [R_EMPL_ID] [varbinary](256) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [LNAME] [varchar](25) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [FNAME] [varchar](20) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [NAME_INITIALS] [varchar](5) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [HIRE_EFF_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [IBM_START_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [TERM_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR_SERIAL_NUM] [varbinary](256) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR_LNAME] [varchar](25) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR_INITIALS] [varchar](5) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [JOB_FAM] [varchar](12) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [JOB_FAM_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [SAL_BAND] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [LVL_DT_1] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DIVISION] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DIVISION_START_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DEPT] [varchar](12) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DEPT_START_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DEPT_SUF_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [FLSA_STAT] [varchar](3) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [EXEMPT_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [POS_CODE] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [POS_DESC] [varchar](35) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [POS_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [REG_TEMP] [char](1) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [STAT3] [varchar](1) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [EMPL_STAT3_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [STATUS] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [EMPL_STAT_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [STD_HRS] [varchar](16) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [WORK_SCHD_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [LOA_BEG_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [LOA_END_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [LOA_TYPE] [varchar](3) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [LVL_SUFFIX] [varchar](1) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DIVISION_FROM] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [WORK_OFF] [varchar](15) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [CURR_DIV_FUNC_CODE] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [CURR_REP_LVL_CODE] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [PREV_DIV_FUNC_CODE] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [PREV_REP_LVL_CODE] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR2_LNAME] [varchar](25) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR2_INITIALS] [varchar](5) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR3_LNAME] [varchar](25) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR3_INITIALS] [varchar](5) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [HIRE_TYPE] [char](1) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [HIRE_PRGM] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [SEPRSN] [varchar](2) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DEPT_FROM] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [VACELGD] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [CMPLN] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [BLDG_ID] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DEPT_SHIFT_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [DEPT_SHIFT_1] [char](1) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [MGR_FLAG] [char](1) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [SALARY] [varbinary](256) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [SALARY_DT] [varchar](8) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [CREATION_DATE] [datetime] NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [CREATED_BY] [varchar](35) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [ASTYP] [varchar](5) NULL
ALTER TABLE [dbo].[XX_R22_CERIS_FILE_STG1] ALTER COLUMN [ASNTYP] [varchar](5) NULL


GO

SET ANSI_PADDING OFF
GO


