-- CR2577 (CP600000825)
-- 05/2010
-- Add (append) two (2) new columns to the end of existing table XX_R22_CERIS_FILE_STG_ARCHIVAL

USE IMAPSStg
GO

ALTER TABLE dbo.XX_R22_CERIS_FILE_STG_ARCHIVAL ADD ASTYP varchar(5) NULL
GO

ALTER TABLE dbo.XX_R22_CERIS_FILE_STG_ARCHIVAL ADD ASNTYP varchar(5) NULL
GO
