-- CR-10364 Add new control point for the FTP to the new SABRIX system

USE IMAPSstg

-- domain_lookup_id must = 25
INSERT INTO 
imapsstg.dbo.xx_lookup_domain (LOOKUP_DOMAIN_DESC,DOMAIN_CONSTANT,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE)
values ('SABRIX Control Points', 'LD_SABRIX_FEED_CTRL_PT', SUSER_SNAME(), GETDATE(), NULL, NULL)

-- presentation order must = 33
INSERT INTO imapsstg.dbo.xx_lookup_detail
  VALUES(1,'SABRIX','Sabrix Interface',33,SUSER_SNAME(),GETDATE(),NULL,NULL)


select top 5 * from imapsstg.dbo.xx_lookup_domain order by lookup_domain_id desc

-- BEFORE
SELECT * FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL
 WHERE LOOKUP_DOMAIN_ID = 25
   ORDER BY PRESENTATION_ORDER

INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-001', 'Load Invoice headers into summary staging table', 1, SUSER_SNAME(), GETDATE())
   
INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-002', 'Validate and update CMR data', 2, SUSER_SNAME(), GETDATE())
   
INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-003', 'Load Invoice detail into detail staging table', 3, SUSER_SNAME(), GETDATE())
   
INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-004', 'Create SABRIX files', 4, SUSER_SNAME(), GETDATE())         

INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-005', 'Load SENT table with new invoices', 5, SUSER_SNAME(), GETDATE())

INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-006', 'FTP Sabrix files', 6, SUSER_SNAME(), GETDATE())

INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(25, 'SABRIX-007', 'Email transaction file', 7, SUSER_SNAME(), GETDATE())


GO


-- AFTER
SELECT * FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL
 WHERE LOOKUP_DOMAIN_ID = 7
   ORDER BY PRESENTATION_ORDER

