UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"sabrix16_hdr,sabrix16_lin,sabrix16_trx"', MODIFIED_BY = SUSER_SNAME(), MODIFIED_DATE = GETDATE() WHERE PARAMETER_NAME = 'CFF_FILES' and INTERFACE_NAME_CD = 'SABRIX'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"2,0,0"', MODIFIED_BY = SUSER_SNAME(), MODIFIED_DATE = GETDATE() WHERE PARAMETER_NAME = 'SQL_TO_EBCDIC' and INTERFACE_NAME_CD = 'SABRIX'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '2', MODIFIED_BY = SUSER_SNAME(), MODIFIED_DATE = GETDATE() WHERE PARAMETER_NAME = 'ELAPSED'


DELETE 
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE PARAMETER_ID IN 
(SELECT PID FROM 
(select PARAMETER_NAME, COUNT(*) AS CNT, MAX(PARAMETER_ID) AS PID
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD LIKE 'SABRIX'
AND PARAMETER_NAME NOT LIKE 'XX_SABRIX%'
GROUP BY PARAMETER_NAME) X
WHERE CNT > 1) 

