-- /*
--WHERE THE BATCH FILE TO RUN CFF IS LOCATED
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_EXE','D:\APPS_TO_COMPILE\CFF\SABRIX.BAT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','FTP_DIR','D:\IMAPS_DATA\Interfaces\PROCESS\SABRIX\',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','ARCHIVE_DIR','D:\IMAPS_DATA\Interfaces\ARCHIVE\SABRIX\',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHERE THE JAVA PROGRAM WILL PUT THE SABRIX EBCDIC FILE; MUST MATCH FILE SPECIFIED IN BATCH FILE
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_JAVA_DATA_FILE','SABRIX_OUT.FIL',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHERE THE JAVA PROGRAM WILL PUT THE SABRIX ASCII FILE; MUST MATCH JAVA DATA FILE PLUS EXTENSION ".TXT"
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_JAVA_TEXT_FILE','SABRIX_OUT_FIL.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHERE THE JAVA PROGRAM WILL PUT THE SABRIX TRANSACTION FILE; MUST MATCH VALUE IN THE TRX.PROPERTIES FILE ".TXT"
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_TRX_FILE','SABRIX_TRX.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--SPECIFY CFF LOG FILE AND LOCATION
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_CFF_LOG_FILE','D:\APPS_TO_COMPILE\CFF\CFF_SABRIX.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHAT TO CALL FILE TO BE FTP'D; MUST MATCH FTP COMMANDS
-- PROD IS (SLIP with a P) SLIP.PRE.FEEDER.CMFDS.INPUT.ORIG  note: SLIP.PRE.FEEDER.CMFDS.INPUT.ORIG(+1) IN THE FTP COMMAND FILE
-- TEST IS (SLIT with a T) SLIT.PRE.FEEDER.CMFDS.INPUT.ORIG  note: SLIT.PRE.FEEDER.CMFDS.INPUT.ORIG(+1) IN THE FTP COMMAND FILE
-- DEV IS kar12.imaps.sabrix.test  note: kar12.imaps.sabrix.test IN THE FTP COMMAND FILE
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_FTP_FILE','SLIT.PRE.FEEDER.CMFDS.INPUT.ORIG',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)
-- UPDATE  imapsstg.dbo.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'kar12.imaps.sabrix.test' WHERE PARAMETER_NAME = 'SABRIX_FTP_FILE'

--CUSTOM COMMAND FILE FOR SABRIX
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_FTP_COMMAND_FILE','D:\IMAPS_DATA\NotShared\SABRIX_FTP_COMMANDS.txt',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--SPECIFY FTP LOG FILE AND LOCATION
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_FTP_LOG_FILE','D:\IMAPS_DATA\NotShared\SABRIX_FTP_LOG.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--SPECIFY FTP INI FILE AND LOCATION FOR FILE THAT CONTAINS FTP_CHECK SCRIPT SUCCESS PARAMETERS
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SABRIX_FTP_INI_FILE','D:\IMAPS_DATA\NotShared\SABRIX_FTP.INI',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--NEED TRANSFER FILES PARAMETER
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','TRANSFER_FILES','NO',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- */

INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','INT_SRC_OWNER','hao.tong@us.ibm.com;george.alvarez@us.ibm.com',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','INT_DEST_OWNER','hao.tong@us.ibm.com;george.alvarez@us.ibm.com',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','COMPANY_ID','1',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);


/*  THIS SQL YIELDS THE INSERT STATEMENTS BELOW ***  DO NOT RUN DURING DEPLOY

SELECT 'INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES(' + 
'(SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = ' + CHAR(39) +'SABRIX' + CHAR(39) 
+'),'+ CHAR(39)+'SABRIX' + CHAR(39) +',' + CHAR(39)+ PARAMETER_NAME+ CHAR(39)+ ',' +
 CHAR(39)+ replace(PARAMETER_VALUE,'FDS_CCS','SABRIX,') + CHAR(39)+
',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);'
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
  WHERE INTERFACE_NAME_CD = 'FDS/CCS'
  AND CHARINDEX('GLIM',PARAMETER_NAME)=0
    AND CHARINDEX('CONFRMCD',PARAMETER_NAME)= 0
  AND CHARINDEX('FDS_FTP',PARAMETER_VALUE)=0
  AND CHARINDEX('CCS_FTP',PARAMETER_VALUE)=0
  AND CHARINDEX('JAVA_',PARAMETER_NAME) = 0
   AND CHARINDEX('CCS_FTP',PARAMETER_NAME)=0
  AND CHARINDEX('FDS_FTP',PARAMETER_NAME)=0
  AND CHARINDEX('CCS_02',PARAMETER_NAME)=0
 AND CHARINDEX('SABRIX',PARAMETER_NAME)=0
 AND CHARINDEX('PARAM', PARAMETER_NAME)=0
 AND CHARINDEX('DIR', PARAMETER_NAME)=0 
 
 ****/

/*************************** THESE PARAMETERS WILL REMAIN FDS/CCS SO THAT WE ONLY HAVE TO MAINTAIN ONE LIST ************************************

INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','DFLT_MACHINE_TYPE','GA70',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','DFLT_PRODUCT_ID','5696398',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','COLL_OFF','28W',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','COLL_DIV','12',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','DFLT_TC_TAX','38',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','DFLT_TC_PROD_CATGRY','16',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','DFLT_TC_AGRMNT','G',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','OHW_TC_TAX','01',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','OHW_TC_PROD_CATGRY','16',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','OHW_TC_AGRMNT','A',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','OSW_TC_TAX','23',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','OSW_TC_PROD_CATGRY','08',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','OSW_TC_AGRMNT','F',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','WEB_TC_TAX','86',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','WEB_TC_PROD_CATGRY','16',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','WEB_TC_AGRMNT','G',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','CSP_ACCT_ID','48-79-08',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','CSP_ACCT_ID','49-79-08',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SCH_BILL_OHW_ACCT_ID','48-79-10',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','SCH_BILL_OSW_ACCT_ID','48-79-11',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','TRANSFER_FILES','NO',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_I_COL_BO','28W',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_C_AR_DIV_MAJOR','2',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_I_ACCTG_PROC_REG','F',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_I_SOURCE_TRANSM','FED',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_F_BILL_DISPRS','2',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_I_SOURCE','142',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_C_BILL','016',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_I_BUSINESS_TYPE','T0',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_C_ORIGIN','9',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_C_LOCAL_APPLIC','1',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_I_COLL_OFF','28W',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','16_C_COLL_DIV','12',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_I_COL_BO','28W',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_C_AR_DIV_MAJOR','2',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_I_ACCTG_PROC_REG','F',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_I_SOURCE_TRANSM','NIA',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_F_BILL_DISPRS','2',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_I_SOURCE','142',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_C_BILL','01M',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_I_BUSINESS_TYPE','T0',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_C_ORIGIN','K',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_C_LOCAL_APPLIC','1',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_I_COLL_OFF','28W',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);
INSERT INTO imapsstg.dbo.XX_PROCESSING_PARAMETERS VALUES((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','1M_C_COLL_DIV','12',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL);

****************************************************************************************** DO NOT ADD THESE ROWS ******/

/*
-- dev for now
update  imapsstg.dbo.XX_PROCESSING_PARAMETERS
set parameter_value = 'kar12.imaps.sabrix.test'
where parameter_name = 'SABRIX_FTP_FILE'

Select * FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'SABRIX' AND
CHARINDEX('FDS', PARAMETER_NAME) > 0

SELECT *
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
 WHERE INTERFACE_NAME_CD = 'SABRIX'
   AND PARAMETER_NAME = 'FTP_DIR'
*/      
Select * FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'SABRIX' AND
CHARINDEX('SABRIX', PARAMETER_NAME) > 0