--note:  not sure what parameters you already have; these are provided just in case
-- structure is select before, insert, select after
-- also an update, in cas you need it


-- BEFORE : THERE SHOULD BE NONE

SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='FTP_COMMAND_EXE'

-- INSERT
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','FTP_COMMAND_EXE','D:\IMAPS_DATA\Interfaces\PROGRAMS\SABRIX\SABRIX_FTP.BAT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- AFTER : THERE SHOULD BE ONE
SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='FTP_COMMAND_EXE'
	

-- BEFORE : THERE SHOULD BE NONE

SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='FTP_LOG_DIR'

-- INSERT
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','FTP_LOG_DIR','D:\IMAPS_DATA\Interfaces\LOGS\SABRIX\',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- AFTER : THERE SHOULD BE ONE
SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='FTP_LOG_DIR'

-- BEFORE : THERE SHOULD BE NONE

SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='FTP_INI_FILE'

-- INSERT
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'SABRIX'),'SABRIX','FTP_INI_FILE','D:\IMAPS_DATA\Interfaces\PROGRAMS\SABRIX\sabrix_ftp.ini',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- AFTER : THERE SHOULD BE ONE
SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='FTP_INI_FILE'

	
-- PROBABLY NEED THIS.  MAKE SURE IT MATCHES WHERE YOU PUT THE WINSCP FILE.
--BEFORE
SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='SABRIX_FTP_COMMAND_FILE'

update 	imapsstg.dbo.XX_PROCESSING_PARAMETERS set PARAMETER_VALUE =  'D:\IMAPS_DATA\Props\SABRIX\sabrix_winscp.txt'
		  WHERE PARAMETER_NAME = 'SABRIX_FTP_COMMAND_FILE'

--AFTER	
SELECT PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='SABRIX'
	AND PARAMETER_NAME='SABRIX_FTP_COMMAND_FILE'