USE IMAPSSTG
DROP VIEW [dbo].[XX_CLS_DOWN_BURDEN_RECONCILE_VW]
GO
SET ANSI_NULLS ON 
GO
SET QUOTED_IDENTIFIER ON
GO
 

 




/* 
Used by Control report : CLS Down Burden reconciliation.imr
              Catalog : Control Points.cat 
	 Folder: Control Point Views\Xx Cls Down Burden Reconcile 2
*/

CREATE View [dbo].[XX_CLS_DOWN_BURDEN_RECONCILE_VW] AS
	SELECT     cls_down.CONTRACT_NUM, pl.L1_PROJ_SEG_ID, pl.PL_ACTUAL_BURDEN, 
	ISNULL(pl.PL_VARIANCE_BURDEN, 0) PL_VARIANCE_BURDEN, 0 NONE, cls_down.CLS_TOTAL_Burden
	FROM    (SELECT     LEFT(l.PROJ_ID, 4) AS L1_PROJ_SEG_ID, SUM(SUB_ACT_AMT) AS PL_ACTUAL_BURDEN, 
			SUM(CASE proj.S_PROJ_RPT_DC
					WHEN 'DIRECT PROJECT' THEN SUB_TGT_AMT - SUB_ACT_AMT 
					ELSE  0  END) AS PL_VARIANCE_BURDEN
			FROM          [IMAPS].Deltek.PROJ_BURD_SUM l INNER JOIN
						(SELECT     TOP 1 *
						FROM          [IMAPSstg].[dbo].[XX_CLS_DOWN_VW]) m 
						ON l.FY_CD = m.FY_SENT AND l.PD_NO = CAST(m.MONTH_SENT AS INTEGER)
					INNER JOIN  [IMAPS].Deltek.PROJ proj ON l.PROJ_ID = proj.PROJ_ID
			GROUP BY LEFT(l.PROJ_ID, 4)) pl 
		FULL OUTER JOIN
			(SELECT     CONTRACT_NUM, L1_PROJ_SEG_ID, 
				SUM(ISNULL(GA_AMT, 0) + ISNULL(OVERHEAD_AMT, 0)) AS CLS_TOTAL_Burden
			FROM         IMAPSstg.dbo.XX_CLS_DOWN
			WHERE      L1_PROJ_SEG_ID IS NOT NULL
			GROUP BY L1_PROJ_SEG_ID, CONTRACT_NUM) cls_down 
		ON pl.L1_PROJ_SEG_ID = cls_down.L1_PROJ_SEG_ID
UNION ALL
	SELECT     LEFT(ACCT_ID, 5) AS CONTRACT_NUM, 'ACCOUNT' AS L1_PROJ_SEG_ID, 
		SUM(CASE RIGHT(ACCT_ID, 2) 
				WHEN 'CR' THEN AMT 
				ELSE 0 END) AS GL_Actual_Burden, 
		SUM(CASE RIGHT(ACCT_ID, 2) 
				WHEN 'RV' THEN AMT 
				ELSE 0 END) AS GL_VARIANCE_Burden,
		(SELECT     SUM(CASE RIGHT(IMAPS_ACCT, 2) WHEN 'CR' THEN DOLLAR_AMT ELSE 0 END)
		FROM          IMAPSstg.dbo.XX_CLS_DOWN
		WHERE      LEFT(IMAPS_ACCT, 5) = LEFT(ACCT_ID, 5)) AS CLS_Actual_Burden,
		(SELECT     SUM(CASE RIGHT(IMAPS_ACCT, 2) WHEN 'RV' THEN DOLLAR_AMT ELSE 0 END)
		FROM          IMAPSstg.dbo.XX_CLS_DOWN
		WHERE      LEFT(IMAPS_ACCT, 5) = LEFT(ACCT_ID, 5)) AS CLS_VARIANCE_Burden
	FROM        [IMAPS].Deltek.GL_POST_SUM n INNER JOIN
			(SELECT     TOP 1 *
						FROM       [IMAPSstg].[dbo].[XX_CLS_DOWN_VW]) o
						ON n.FY_CD = o.FY_SENT AND n.PD_NO = CAST(o.MONTH_SENT AS INTEGER)
	WHERE     RIGHT(ACCT_ID, 2) IN ('CR', 'RV') AND LEFT(ACCT_ID, 2) = 'PA' 
	GROUP BY LEFT(ACCT_ID, 5)










 

 

GO
 

