USE [IMAPSStg]
GO

/****** Object:  View [dbo].[XX_CLS_REPORTING_DIV_VW]    Script Date: 9/9/2022 10:12:45 AM ******/
DROP VIEW [dbo].[XX_CLS_REPORTING_DIV_VW]
GO

/****** Object:  View [dbo].[XX_CLS_REPORTING_DIV_VW]    Script Date: 9/9/2022 10:12:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO


/* 
Used by CLS Interface to return implied reporting division based on MAJOR

*/

CREATE VIEW [dbo].[XX_CLS_REPORTING_DIV_VW]
AS

SELECT LEFT(PARAMETER_NAME,2) AS DIV, LEFT(PARAMETER_VALUE,3) AS MAJOR,
CASE RIGHT(PARAMETER_NAME,1) 
 WHEN '3' THEN 'REV'
 WHEN '4' THEN 'EXP'
END AS CLASS
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'CLS' 
AND ISNUMERIC(PARAMETER_VALUE)=1
AND LEN(LTRIM(RTRIM(PARAMETER_VALUE)))=11
AND LEN(PARAMETER_NAME)=3
AND RIGHT(PARAMETER_NAME,1) IN ('3','4')


GO


