ALTER TABLE IMAPSSTG.[dbo].[XX_CLS_DOWN_YTD_ARCHIVE] ADD [GENL_ID] [varchar](50) NULL
ALTER TABLE IMAPSSTG.[dbo].[XX_CLS_DOWN_YTD_ARCHIVE] ADD [UDEF_TXT] [varchar](20) NULL
ALTER TABLE IMAPSSTG.[dbo].[XX_CLS_DOWN_YTD_ARCHIVE] ADD [FULL_PROJ_ID] [varchar](50) NULL
