/****** Object:  Table [dbo].[XX_CLS_DOWN_ACCT_MEMO_MAPPING]    Script Date: 02/03/2007 1:50:22 AM ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[XX_CLS_DOWN_ACCT_MEMO_MAPPING]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[XX_CLS_DOWN_ACCT_MEMO_MAPPING]
GO

if not exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[XX_CLS_DOWN_ACCT_MEMO_MAPPING]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
 BEGIN
CREATE TABLE [dbo].[XX_CLS_DOWN_ACCT_MEMO_MAPPING] (
	[ROW_NUM] [int] IDENTITY (1, 1) NOT NULL ,
	[IMAPS_ACCT] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CLS_MAJOR] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CLS_MINOR] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CLS_SUB_MINOR] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CONTRACT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CUSTOMER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJECT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MACHINE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PRODUCT_ID] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[APPLY_BURDEN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MULTIPLIER] [smallint] NULL ,
	CONSTRAINT [PK_XX_CLS_DOWN_ACCT_MEMO_MAPPING] PRIMARY KEY  CLUSTERED 
	(
		[ROW_NUM]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
) ON [PRIMARY]
END

GO


--subcontractor accruals memo entry
INSERT INTO XX_CLS_DOWN_ACCT_MEMO_MAPPING
(IMAPS_ACCT, CLS_MAJOR, CLS_MINOR, CLS_SUB_MINOR, CONTRACT, CUSTOMER, PROJECT, MACHINE_TYPE, PRODUCT_ID, APPLY_BURDEN, MULTIPLIER )
SELECT '43-14-91', '817', '0370', '0000', NULL, NULL, 'Y', NULL, NULL, NULL, 1
GO

INSERT INTO XX_CLS_DOWN_ACCT_MEMO_MAPPING
(IMAPS_ACCT, CLS_MAJOR, CLS_MINOR, CLS_SUB_MINOR, CONTRACT, CUSTOMER, PROJECT, MACHINE_TYPE, PRODUCT_ID, APPLY_BURDEN, MULTIPLIER )
SELECT '43-14-91', '817', '8440', '0000', NULL, NULL, 'Y', NULL, NULL, NULL, -1
GO