USE [IMAPSStg]
GO

/****** Object:  StoredProcedure [dbo].[XX_R22_FIWLR_MISCODE_VALIDATE_RECORDS_SP]    Script Date: 01/09/2018 13:42:52 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XX_R22_FIWLR_MISCODE_VALIDATE_RECORDS_SP]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[XX_R22_FIWLR_MISCODE_VALIDATE_RECORDS_SP]
GO

USE [IMAPSStg]
GO

/****** Object:  StoredProcedure [dbo].[XX_R22_FIWLR_MISCODE_VALIDATE_RECORDS_SP]    Script Date: 01/09/2018 13:42:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO






CREATE PROCEDURE [dbo].[XX_R22_FIWLR_MISCODE_VALIDATE_RECORDS_SP] (
@in_STATUS_RECORD_NUM integer,
@in_VOUCHER_NO VARCHAR(13),
@in_UNIQUE_RECORD_NUM integer,
@out_STATUS_DESCRIPTION sysname = NULL
)
AS
BEGIN
/************************************************************************************************  
Name:       	XX_R22_FIWLR_MISCODE_VALIDATE_RECORDS_SP 
Author:     	TP

on change: */

                                                                 
/************************************************************************************************/  

	DECLARE	@SP_NAME         sysname,
		@DIV_22_COMPANY_ID 	 varchar(10),
        @IMAPS_error_number      integer,
        @SQLServer_error_code    integer,
        @error_msg_placeholder1  sysname,
        @error_msg_placeholder2  sysname,
		@INTERFACE_NAME		 sysname,
		@ret_code		 int,
		@count			 int,
		@inc_exc_fl 		char(1),
		@FIWLR_OFFSET_ACCT_ID	varchar(12),
		@change			varchar(10)                   

	SELECT @DIV_22_COMPANY_ID = PARAMETER_VALUE
	  FROM dbo.XX_PROCESSING_PARAMETERS
	 WHERE PARAMETER_NAME = 'COMPANY_ID'
	   AND INTERFACE_NAME_CD = 'FIWLR_R22'

	SET @inc_exc_fl = 'I'
	SET @INTERFACE_NAME = 'FIWLR_R22'
	SET @SP_NAME = 'XX_R22_FIWLR_MISCODE_UPDATE_SP'

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET 	REFERENCE1 = 'U',
		REFERENCE2 = ''
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
		AND	( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)

	


	/*FEEDBACK UPDATE */
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - ACCT_ID'

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'acct,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	0 =
	(	SELECT COUNT(1)
		FROM IMAR.DELTEK.ACCT
		WHERE ACCT_ID = FIWLR.ACCT_ID
	)
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR
	
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - ORG_ID & PROJ_ABBRV_CD'
	
	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'org,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
		AND	( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	--AND	ORG_ABBR_CD IS NOT NULL
	AND	0 =
	(	SELECT COUNT(1)
		FROM 	IMAR.DELTEK.ORG
		WHERE	COMPANY_ID = @DIV_22_COMPANY_ID AND ORG_ABBRV_CD = ISNULL(FIWLR.ORG_ABBR_CD, '?') AND ORG_ABBRV_CD<>''
		AND ((FIWLR.DIVISION = '24' AND L1_ORG_SEG_ID = '24') or (FIWLR.DIVISION <> '24' AND L1_ORG_SEG_ID = '22'))   --CR7905
	)
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR
	
	
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - PROJ_ABBRV_CD'
	
	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'proj,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	--AND	PROJ_ABBR_CD IS NOT NULL
	AND	0 =
	(	SELECT	COUNT(1)
		FROM 	IMAR.DELTEK.PROJ
		WHERE	COMPANY_ID = @DIV_22_COMPANY_ID AND PROJ_ABBRV_CD = ISNULL(FIWLR.PROJ_ABBR_CD, '?') AND PROJ_ABBRV_CD<>''
	)
	/*--CR for 9X-XX-XX accounts
	AND left(isnull(acct_id, '?'),1) not in ('9')
	*/
	--and not a blank project with non project required account
	AND NOT (
			LEN(ISNULL(fiwlr.PROJ_ABBR_CD, ''))=0 
			AND fiwlr.ACCT_ID IN (SELECT ACCT_ID 
								  FROM IMAR.DELTEK.ACCT 
								  WHERE ACCT_ID=fiwlr.ACCT_ID 
								  AND PROJ_REQD_FL='N')
			)

	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR

	
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - ACCT_ID & PROJ_ABBRV_CD'

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'acct_pag,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
		AND	( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	LEN(ISNULL(ACCT_ID, ''))<>0
	AND	LEN(ISNULL(PAG_CD, ''))<>0
	AND	0 =
	(	SELECT COUNT(1)
		FROM 	IMAR.DELTEK.ACCT_GRP_SETUP
		WHERE	COMPANY_ID = @DIV_22_COMPANY_ID 
		AND ACCT_ID = FIWLR.ACCT_ID
		AND	ACCT_GRP_CD = FIWLR.PAG_CD
	)
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR


	
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - ACCT_ID & ORG_ID'

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'acct_org,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	LEN(ISNULL(ACCT_ID, ''))<>0
	AND	LEN(ISNULL(ORG_ID, ''))<>0
	AND	0 =
	(	SELECT COUNT(1)
		FROM 	IMAR.DELTEK.ORG_ACCT
		WHERE	ACCT_ID = FIWLR.ACCT_ID
		AND	ORG_ID = FIWLR.ORG_ID
	)


	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR

	
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - PROJ ALLOW_CHARGES_FL'	

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'proj_chg_fl,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)	
	AND	LEN(ISNULL(PROJ_ABBR_CD, ''))<>0
	AND	1 =
	(	SELECT COUNT(1) 
		FROM 	IMAR.DELTEK.PROJ
		WHERE	COMPANY_ID = @DIV_22_COMPANY_ID AND PROJ_ABBRV_CD = FIWLR.PROJ_ABBR_CD
		AND		ALLOW_CHARGES_FL = 'N'
	)
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR


	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - PROJ ACTIVE_FL'	

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'proj_inactive,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	LEN(ISNULL(PROJ_ABBR_CD, ''))<>0
	AND	1 =
	(	SELECT COUNT(1)
		FROM 	IMAR.DELTEK.PROJ
		WHERE	COMPANY_ID = @DIV_22_COMPANY_ID AND PROJ_ABBRV_CD = FIWLR.PROJ_ABBR_CD
		AND	ACTIVE_FL = 'N'
	)
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR


	
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - ORG ACTIVE_FL'	

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'org_inactive,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND	( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	       @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	LEN(ISNULL(ORG_ABBR_CD, ''))<>0
	AND	1 =
	(	SELECT COUNT(1)
		FROM 	IMAR.DELTEK.ORG
		WHERE	COMPANY_ID = @DIV_22_COMPANY_ID AND ORG_ABBRV_CD = FIWLR.ORG_ABBR_CD
		AND ((FIWLR.DIVISION = '24' AND L1_ORG_SEG_ID = '24') or (FIWLR.DIVISION <> '24' AND L1_ORG_SEG_ID = '22'))   --CR7905
		AND	ACTIVE_FL = 'N'
	)

	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR

	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - ACCT ACTIVE_FL'	

	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'acct_inactive,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND	( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	       @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	LEN(ISNULL(ACCT_ID, ''))<>0
	AND	1 =
	(	SELECT COUNT(1)
		FROM 	IMAR.DELTEK.ACCT
		WHERE	ACCT_ID = FIWLR.ACCT_ID
		AND	ACTIVE_FL = 'N'
	)

	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR
	
	
    --CR9365 begin
	SET @IMAPS_ERROR_NUMBER = 204 -- ATTEMPT TO %1 %2 FAILED.
	SET @ERROR_MSG_PLACEHOLDER1 = 'UPDATE FIWLR'
	SET @ERROR_MSG_PLACEHOLDER2 = 'WITH MISCODE FEEDBACK - Vendor'	
	
	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET	REFERENCE2 = CAST(REFERENCE2 + 'vendor,' AS VARCHAR(125))
	FROM	XX_R22_FIWLR_USDET_MISCODES FIWLR
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND SOURCE = '005'
	AND RTRIM(ISNULL(VENDOR_ID,''))= ''
	
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR
	--CR9365 end


	UPDATE 	XX_R22_FIWLR_USDET_MISCODES
	SET 	REFERENCE2 = 'valid'
	WHERE	STATUS_REC_NO = @in_STATUS_RECORD_NUM
	AND		( @in_UNIQUE_RECORD_NUM is not NULL and IDENT_REC_NO = @in_UNIQUE_RECORD_NUM 
	       OR 
	          @in_VOUCHER_NO is not NULL and  VOUCHER_NO = @in_VOUCHER_NO)
	AND	LEN(REFERENCE2) = 0
	
	SELECT @SQLSERVER_ERROR_CODE = @@ERROR	
	IF @SQLSERVER_ERROR_CODE <> 0 GOTO ERROR




RETURN 0

ERROR:

PRINT @out_STATUS_DESCRIPTION

EXEC dbo.XX_ERROR_MSG_DETAIL
   @in_error_code           = @IMAPS_error_number,
   @in_display_requested    = 1,
   @in_SQLServer_error_code = @SQLServer_error_code,
   @in_placeholder_value1   = @error_msg_placeholder1,
   @in_placeholder_value2   = @error_msg_placeholder2,
   @in_calling_object_name  = @SP_NAME,
   @out_msg_text            = @out_STATUS_DESCRIPTION OUTPUT

PRINT @out_STATUS_DESCRIPTION

RETURN 1


END












GO

