USE [IMAPSStg]
GO

/****** Object:  StoredProcedure [dbo].[XX_R22_CLS_DOWN_ARCHIVE_FILES_SP]    Script Date: 5/7/2020 12:33:25 PM ******/
DROP PROCEDURE [dbo].[XX_R22_CLS_DOWN_ARCHIVE_FILES_SP]
GO

/****** Object:  StoredProcedure [dbo].[XX_R22_CLS_DOWN_ARCHIVE_FILES_SP]    Script Date: 5/7/2020 12:33:25 PM ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO





CREATE PROCEDURE [dbo].[XX_R22_CLS_DOWN_ARCHIVE_FILES_SP]
( 
@in_STATUS_RECORD_NUM   integer, 
@out_SystemError        integer = NULL OUTPUT, 
@out_STATUS_DESCRIPTION varchar(275) = NULL OUTPUT
) 
AS

/************************************************************************************************  
Name:       XX_R22_CLS_DOWN_ARCHIVE_FILES_SP
Created by: HVT
Created:    10/27/2008
Purpose:    Archive all output files generated by the interface run.

            Called by XX_R22_CLS_DOWN_RUN_INTERFACE_SP.
            Adapted from XX_CLS_DOWN_ARCHIVE_FILES_SP.

Notes:      XX_R22_CLS_DOWN_YTD_ARCHIVE records are inserted for each interface run in
            the program XX_R22_CLS_DOWN_LOAD_STAGE_SP.

CP600000465 10/27/2008 Reference BP&S Service Request CR1656
            Leverage the existing CLS Down interface for Division 16 to develop an interface
            between Costpoint and CLS to meet Division 22 (aka Research) requirements.

************************************************************************************************/

BEGIN

DECLARE	@SP_NAME                 sysname,
        @ERROR_DIR               sysname,
        @PROCESS_DIR             sysname,
        @ARCH_DIR                sysname,
        @FILE_ID                 sysname,
        @cmd_str                 varchar(500),
        @IMAPS_error_number      integer,
        @SQLServer_error_code    integer,
        @error_msg_placeholder1  sysname,
        @error_msg_placeholder2  sysname,
        @ret_code                integer

-- Set local constants
SET @SP_NAME = 'XX_R22_CLS_DOWN_ARCHIVE_FILES_SP'


PRINT '***********************************************************************************************************************'
PRINT '     START OF ' + @SP_NAME
PRINT '***********************************************************************************************************************'

SET @IMAPS_error_number = 204 -- Attempt to %1 %2 failed.
SET @error_msg_placeholder1 = 'archive'
SET @error_msg_placeholder2 = 'R22 CLS Down output file ' + CAST(@in_STATUS_RECORD_NUM as varchar(15))

PRINT 'Attempt to archive all output files ...'

PRINT 'DETERMINING WHICH DRIVES WE ARE WORKING WITH'

DECLARE @DATA_DRIVE nvarchar(255), @PROG_DRIVE nvarchar(255)

DECLARE @MyTbl TABLE(EnvVar NVARCHAR(255))

INSERT INTO @MyTbl exec xp_cmdshell 'echo %DATA_DRIVE%'
SET @DATA_DRIVE = (SELECT TOP 1 EnvVar from @MyTbl)
DELETE FROM @MyTbl

INSERT INTO @MyTbl exec xp_cmdshell 'echo %PROG_DRIVE%'
SET @PROG_DRIVE = (SELECT TOP 1 EnvVar from @MyTbl)


  
SELECT @ERROR_DIR = REPLACE(PARAMETER_VALUE,'%DATA_DRIVE%',@DATA_DRIVE) 
  FROM dbo.XX_PROCESSING_PARAMETERS
 WHERE INTERFACE_NAME_CD = 'CLS_R22' 
   AND PARAMETER_NAME = 'LO_DIR'

SELECT @PROCESS_DIR = REPLACE(PARAMETER_VALUE,'%DATA_DRIVE%',@DATA_DRIVE) 
  FROM dbo.XX_PROCESSING_PARAMETERS
 WHERE INTERFACE_NAME_CD = 'CLS_R22' 
   AND PARAMETER_NAME = 'PROCESS_DIR'

SELECT @ARCH_DIR = REPLACE(PARAMETER_VALUE,'%DATA_DRIVE%',@DATA_DRIVE) 
  FROM dbo.XX_PROCESSING_PARAMETERS
 WHERE INTERFACE_NAME_CD = 'CLS_R22' 
   AND PARAMETER_NAME = 'ARCH_DIR'

SELECT @FILE_ID = PARAMETER_VALUE 
  FROM dbo.XX_PROCESSING_PARAMETERS
 WHERE INTERFACE_NAME_CD = 'CLS_R22' 
   AND PARAMETER_NAME = 'FILE_ID'

-- Archive ASCII 999-format file

SET @cmd_str = 'MOVE ' + @PROCESS_DIR + 'R22_clsdown.txt ' + @ARCH_DIR + CAST(@in_STATUS_RECORD_NUM as varchar(15)) + '_IMAR_TO_CLS_ASCII.TXT'
PRINT @cmd_str
EXEC @ret_code = master.dbo.XP_CMDSHELL @cmd_str

IF @ret_code <> 0
   BEGIN
      SET @error_msg_placeholder2 = @error_msg_placeholder2 + '_IMAR_TO_CLS_ASCII.TXT'
      GOTO ERROR_HANDLER
   END

-- Archive binary 999-format file

SET @cmd_str = 'COPY /Y ' + @PROCESS_DIR + 'IMAR_TO_CLS.BIN ' + @ARCH_DIR + CAST(@in_STATUS_RECORD_NUM as varchar(15)) + '_IMAR_TO_CLS.BIN'
PRINT @cmd_str
EXEC @ret_code = master.dbo.XP_CMDSHELL @cmd_str

IF @ret_code <> 0
   BEGIN
      SET @error_msg_placeholder2 = @error_msg_placeholder2 + '_IMAR_TO_CLS.BIN'
      GOTO ERROR_HANDLER
   END

-- Archive PARM card file (used in the MVS-bound FTP session)

SET @cmd_str = 'COPY /Y ' + @PROCESS_DIR + 'F' + @FILE_ID + 'PARM* ' + @ARCH_DIR + CAST(@in_STATUS_RECORD_NUM as varchar(15)) + '_F' + @FILE_ID + 'PARM.TXT'
PRINT @cmd_str
EXEC @ret_code = master.dbo.XP_CMDSHELL @cmd_str

IF @ret_code <> 0
   BEGIN
      SET @error_msg_placeholder2 = @error_msg_placeholder2 + '_F' + @FILE_ID + 'PARM.TXT'
      GOTO ERROR_HANDLER
   END

-- Archive file creation error log file

SET @cmd_str = 'MOVE ' + @ERROR_DIR + 'CFF_CLS_R22_APP_R22_clsdown.TXT + CFF_CLS_R22_APP_R22_clsdownparm.txt = CFF_CLS_R22_APP_R22_clsdownsummary.txt'  + @ARCH_DIR + CAST(@in_STATUS_RECORD_NUM as varchar(15)) + '_IMAR_TO_CLS_CFF_LOG.TXT'
PRINT @cmd_str
EXEC @ret_code = master.dbo.XP_CMDSHELL @cmd_str

IF @ret_code <> 0
   BEGIN
      SET @error_msg_placeholder2 = @error_msg_placeholder2 + ' CFF_CLS_R22_APP_R22_clsdownsummary.txt'
      GOTO ERROR_HANDLER
   END

-- Archive interface control file

SET @cmd_str = 'MOVE ' + @PROCESS_DIR + 'IMAR_TO_CLS_DOWN* ' + @ARCH_DIR + CAST(@in_STATUS_RECORD_NUM as varchar(15)) + '_IMAR_TO_CLS_DOWN_SUMMARY.TXT'
PRINT @cmd_str
EXEC master.dbo.XP_CMDSHELL @cmd_str

IF @ret_code <> 0
   BEGIN
      SET @error_msg_placeholder2 = @error_msg_placeholder2 + '_IMAR_TO_CLS_DOWN_SUMMARY.TXT'
      GOTO ERROR_HANDLER
   END

PRINT '***********************************************************************************************************************'
PRINT '     END OF ' + @SP_NAME
PRINT '***********************************************************************************************************************'



RETURN(0)

ERROR_HANDLER:

SET @out_SystemError = @SQLServer_error_code

EXEC dbo.XX_ERROR_MSG_DETAIL
   @in_error_code           = @IMAPS_error_number,
   @in_display_requested    = 1,
   @in_SQLServer_error_code = @SQLServer_error_code,
   @in_placeholder_value1   = @error_msg_placeholder1,
   @in_placeholder_value2   = @error_msg_placeholder2,
   @in_calling_object_name  = @SP_NAME,
   @out_msg_text            = @out_STATUS_DESCRIPTION OUTPUT

RETURN(1)

END



GO


