USE [IMAPSStg]
GO
/****** Object:  StoredProcedure [dbo].[XX_RETRORATE_REMOVE_OBD_FOR_YEAR_SP]    Script Date: 10/24/2007 07:47:55 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[XX_RETRORATE_REMOVE_OBD_FOR_YEAR_SP]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
DROP PROCEDURE [DBO].[XX_RETRORATE_REMOVE_OBD_FOR_YEAR_SP]
GO



CREATE PROCEDURE [dbo].[XX_RETRORATE_REMOVE_OBD_FOR_YEAR_SP] 
( 
@in_YEAR   char(4)
)
/************************************************************************************************  
Name:       	XX_RETRORATE_REMOVE_OBD_FOR_YEAR_SP
Author:     	KM

	exec xx_retrorate_remove_obd_for_year_sp '2007'
************************************************************************************************/  
AS
BEGIN


	INSERT INTO XX_OPEN_BILLING_DETL
	(
	CREATED_DATE,
	XX_TOBE_RESTORED_FL,
	XX_RESTORED_FL,
	SRCE_KEY,
	LVL1_KEY,
	LVL2_KEY,
	LVL3_KEY,
	TRN_PROJ_ID,
	ACCT_ID,
	ORG_ID,
	FY_CD,
	PD_NO,
	SUB_PD_NO,
	S_TRN_TYPE,
	TRN_AMT,
	TRN_HRS,
	TRN_QTY,
	BILL_AMT,
	BILL_HRS,
	BILL_QTY,
	WRITE_OFF_AMT,
	WRITE_OFF_HRS,
	WRITE_OFF_QTY,
	HOLD_AMT,
	HOLD_HRS,
	HOLD_QTY,
	PREV_BILLED_AMT,
	PREV_BILLED_HRS,
	PREV_BILLED_QTY,
	S_ID_TYPE,
	ID,
	NAME,
	BILL_LAB_CAT_CD,
	BILL_LAB_CAT_DESC,
	ITEM_ID,
	ITEM_RVSN_ID,
	ITEM_DESC,
	ITEM_NT,
	TRN_DESC,
	VCHR_NO,
	VCHR_KEY,
	JE_NO,
	REF1_ID,
	REF2_ID,
	AP_INVC_ID,
	COMMENTS,
	TS_DT,
	S_JNL_CD,
	POST_SEQ_NO,
	CASH_BASIS_DOL_AMT,
	S_SOURCE_CD,
	WRITE_OFF_DESC,
	HOLD_REASON_DESC,
	GENL_LAB_CAT_CD,
	GENL_LAB_CAT_DESC,
	MODIFIED_BY,
	TIME_STAMP,
	CLIN_ID,
	CASH_RECPT_NO,
	UNITS_USAGE_DT,
	SALES_TAX_CD,
	S_PRICE_SRCE_CD,
	SRCE_PROJ_ID,
	PRICE_CATLG_CD,
	ITEM_KEY,
	BILL_RT_AMT,
	S_BILL_RT_TYPE_CD,
	MU_BILL_RT_AMT,
	ROWVERSION,
	COMPANY_ID,
	ORIG_BILL_RT_AMT,
	CASH_BASIS_HRS
	)
	SELECT 
	GETDATE() AS CREATED_DATE,
	'N' AS XX_TOBE_RESTORED_FL,
	'N' AS XX_RESTORED_FL,
	SRCE_KEY,
	LVL1_KEY,
	LVL2_KEY,
	LVL3_KEY,
	TRN_PROJ_ID,
	ACCT_ID,
	ORG_ID,
	FY_CD,
	PD_NO,
	SUB_PD_NO,
	S_TRN_TYPE,
	TRN_AMT,
	TRN_HRS,
	TRN_QTY,
	BILL_AMT,
	BILL_HRS,
	BILL_QTY,
	WRITE_OFF_AMT,
	WRITE_OFF_HRS,
	WRITE_OFF_QTY,
	HOLD_AMT,
	HOLD_HRS,
	HOLD_QTY,
	PREV_BILLED_AMT,
	PREV_BILLED_HRS,
	PREV_BILLED_QTY,
	S_ID_TYPE,
	ID,
	NAME,
	BILL_LAB_CAT_CD,
	BILL_LAB_CAT_DESC,
	ITEM_ID,
	ITEM_RVSN_ID,
	ITEM_DESC,
	ITEM_NT,
	TRN_DESC,
	VCHR_NO,
	VCHR_KEY,
	JE_NO,
	REF1_ID,
	REF2_ID,
	AP_INVC_ID,
	COMMENTS,
	TS_DT,
	S_JNL_CD,
	POST_SEQ_NO,
	CASH_BASIS_DOL_AMT,
	S_SOURCE_CD,
	WRITE_OFF_DESC,
	HOLD_REASON_DESC,
	GENL_LAB_CAT_CD,
	GENL_LAB_CAT_DESC,
	MODIFIED_BY,
	TIME_STAMP,
	CLIN_ID,
	CASH_RECPT_NO,
	UNITS_USAGE_DT,
	SALES_TAX_CD,
	S_PRICE_SRCE_CD,
	SRCE_PROJ_ID,
	PRICE_CATLG_CD,
	ITEM_KEY,
	BILL_RT_AMT,
	S_BILL_RT_TYPE_CD,
	MU_BILL_RT_AMT,
	ROWVERSION,
	COMPANY_ID,
	ORIG_BILL_RT_AMT,
	CASH_BASIS_HRS
	FROM IMAPS.DELTEK.OPEN_BILLING_DETL
	WHERE FY_CD=@in_YEAR
	AND	PD_NO=13
	AND SUB_PD_NO=1
	AND	S_JNL_CD='LD'

	IF @@ERROR <> 0
	BEGIN
		PRINT 'ERROR COPYING OBD RECORDS'
		RETURN 1
	END


	DELETE FROM IMAPS.DELTEK.OPEN_BILLING_DETL
	WHERE FY_CD=@in_YEAR
	AND	PD_NO=13
	AND SUB_PD_NO=1
	AND	S_JNL_CD='LD'

	IF @@ERROR <> 0
	BEGIN
		PRINT 'ERROR DELETING OBD RECORDS'
		RETURN 1
	END

	RETURN 0

END




