USE [IMAPSStg]
GO
/****** Object:  StoredProcedure [dbo].[XX_RETRORATE_RESTORE_OBD_SP]    Script Date: 10/24/2007 07:47:55 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[XX_RETRORATE_RESTORE_OBD_SP]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
DROP PROCEDURE [DBO].[XX_RETRORATE_RESTORE_OBD_SP]
GO


CREATE PROCEDURE [dbo].[XX_RETRORATE_RESTORE_OBD_SP] 
/************************************************************************************************  
Name:       	XX_RETRORATE_RESTORE_OBD_SP
Author:     	KM

	exec XX_RETRORATE_RESTORE_OBD_SP 
************************************************************************************************/  
AS
BEGIN


	INSERT INTO IMAPS.DELTEK.OPEN_BILLING_DETL
	(
	SRCE_KEY,
	LVL1_KEY,
	LVL2_KEY,
	LVL3_KEY,
	TRN_PROJ_ID,
	ACCT_ID,
	ORG_ID,
	FY_CD,
	PD_NO,
	SUB_PD_NO,
	S_TRN_TYPE,
	TRN_AMT,
	TRN_HRS,
	TRN_QTY,
	BILL_AMT,
	BILL_HRS,
	BILL_QTY,
	WRITE_OFF_AMT,
	WRITE_OFF_HRS,
	WRITE_OFF_QTY,
	HOLD_AMT,
	HOLD_HRS,
	HOLD_QTY,
	PREV_BILLED_AMT,
	PREV_BILLED_HRS,
	PREV_BILLED_QTY,
	S_ID_TYPE,
	ID,
	NAME,
	BILL_LAB_CAT_CD,
	BILL_LAB_CAT_DESC,
	ITEM_ID,
	ITEM_RVSN_ID,
	ITEM_DESC,
	ITEM_NT,
	TRN_DESC,
	VCHR_NO,
	VCHR_KEY,
	JE_NO,
	REF1_ID,
	REF2_ID,
	AP_INVC_ID,
	COMMENTS,
	TS_DT,
	S_JNL_CD,
	POST_SEQ_NO,
	CASH_BASIS_DOL_AMT,
	S_SOURCE_CD,
	WRITE_OFF_DESC,
	HOLD_REASON_DESC,
	GENL_LAB_CAT_CD,
	GENL_LAB_CAT_DESC,
	MODIFIED_BY,
	TIME_STAMP,
	CLIN_ID,
	CASH_RECPT_NO,
	UNITS_USAGE_DT,
	SALES_TAX_CD,
	S_PRICE_SRCE_CD,
	SRCE_PROJ_ID,
	PRICE_CATLG_CD,
	ITEM_KEY,
	BILL_RT_AMT,
	S_BILL_RT_TYPE_CD,
	MU_BILL_RT_AMT,
	ROWVERSION,
	COMPANY_ID,
	ORIG_BILL_RT_AMT,
	CASH_BASIS_HRS
	)
	SELECT 
		SRCE_KEY,
	LVL1_KEY,
	LVL2_KEY,
	LVL3_KEY,
	TRN_PROJ_ID,
	ACCT_ID,
	ORG_ID,
	FY_CD,
	PD_NO,
	SUB_PD_NO,
	S_TRN_TYPE,
	TRN_AMT,
	TRN_HRS,
	TRN_QTY,
	BILL_AMT,
	BILL_HRS,
	BILL_QTY,
	WRITE_OFF_AMT,
	WRITE_OFF_HRS,
	WRITE_OFF_QTY,
	HOLD_AMT,
	HOLD_HRS,
	HOLD_QTY,
	PREV_BILLED_AMT,
	PREV_BILLED_HRS,
	PREV_BILLED_QTY,
	S_ID_TYPE,
	ID,
	NAME,
	BILL_LAB_CAT_CD,
	BILL_LAB_CAT_DESC,
	ITEM_ID,
	ITEM_RVSN_ID,
	ITEM_DESC,
	ITEM_NT,
	TRN_DESC,
	VCHR_NO,
	VCHR_KEY,
	JE_NO,
	REF1_ID,
	REF2_ID,
	AP_INVC_ID,
	COMMENTS,
	TS_DT,
	S_JNL_CD,
	POST_SEQ_NO,
	CASH_BASIS_DOL_AMT,
	S_SOURCE_CD,
	WRITE_OFF_DESC,
	HOLD_REASON_DESC,
	GENL_LAB_CAT_CD,
	GENL_LAB_CAT_DESC,
	MODIFIED_BY,
	TIME_STAMP,
	CLIN_ID,
	CASH_RECPT_NO,
	UNITS_USAGE_DT,
	SALES_TAX_CD,
	S_PRICE_SRCE_CD,
	SRCE_PROJ_ID,
	PRICE_CATLG_CD,
	ITEM_KEY,
	BILL_RT_AMT,
	S_BILL_RT_TYPE_CD,
	MU_BILL_RT_AMT,
	ROWVERSION,
	COMPANY_ID,
	ORIG_BILL_RT_AMT,
	CASH_BASIS_HRS
	FROM XX_OPEN_BILLING_DETL
	WHERE 
	XX_TOBE_RESTORED_FL = 'Y'
	AND
	XX_RESTORED_FL = 'N'
	AND
	RESTORED_DATE IS NULL	

	IF @@ERROR <> 0
	BEGIN
		PRINT 'ERROR INSERTING OBD RECORDS'
		RETURN 1
	END


	UPDATE XX_OPEN_BILLING_DETL
	SET XX_RESTORED_FL = 'Y',
		RESTORED_DATE = GETDATE()
	WHERE 
	XX_TOBE_RESTORED_FL = 'Y'
	AND
	XX_RESTORED_FL = 'N'
	AND
	RESTORED_DATE IS NULL	 

	IF @@ERROR <> 0
	BEGIN
		PRINT 'ERROR UPDATE XX_OBD RECORDS'
		RETURN 1
	END

	RETURN 0

END




