USE [IMAPSStg]
GO
/****** Object:  StoredProcedure [dbo].[XX_RETRORATE_RESTORE_OBD_FOR_YEAR_SP]    Script Date: 05/06/2008 11:36:39 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[XX_RETRORATE_RESTORE_OBD_FOR_YEAR_SP]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
DROP PROCEDURE [DBO].[XX_RETRORATE_RESTORE_OBD_FOR_YEAR_SP]
GO
