/*****
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_EXE','D:\APPS_TO_COMPILE\GLIM\GLIM.BAT','GEORGE',GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_FTP_DEST_FILE_1','D:\APPS_TO_COMPILE\GLIM\FTP\IMAPFIW.TEST.CONTROL2.FDSCCS','GEORGE',GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_FTP_DEST_FILE_2','D:\APPS_TO_COMPILE\GLIM\FTP\IMAPFIW.TEST.MOD999.PARM','GEORGE',GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_OUT_DEST_FILE_1','D:\APPS_TO_COMPILE\GLIM\OUTPUT\IMAPFIW.TEST.CONTROL2.FDSCCS','GEORGE',GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_OUT_DEST_FILE_2','D:\APPS_TO_COMPILE\GLIM\OUTPUT\IMAPFIW.TEST.MOD999.PARM','GEORGE',GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_FTP_COMMAND_FILE','D:\APPS_TO_COMPILE\GLIM\GLIM_FTP_COMMANDS.txt','GEORGE',GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','GLIM_FTP_LOG_FILE','D:\APPS_TO_COMPILE\GLIM\OUTPUT\GLIM_FTP_LOG.TXT','GEORGE',GETDATE(),NULL,NULL,NULL)


******/

Select * FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'FDS/CCS' AND
left(PARAMETER_NAME,4) = 'GLIM'