	UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	SET PARAMETER_VALUE = 'D:\IMAPS_DATA\Props\CLS\CLS_WINSCP.TXT'
	WHERE INTERFACE_NAME_CD='CLS'
	AND PARAMETER_NAME='FTP_COMMAND_FILE'
	
	INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','FTP_COMMAND_EXE','D:\IMAPS_DATA\Interfaces\PROGRAMS\cls\cls_ftp.bat',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

SELECT 'MAKE SURE THESE FILES ARE WHERE THEY ARE SUPPOSED TO BE' AS READ_THIS_ENTIRE_INSTRUCTION1


	SELECT PARAMETER_NAME, PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='CLS'
	AND PARAMETER_NAME='FTP_COMMAND_FILE'

	SELECT PARAMETER_NAME, PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='CLS'
	AND PARAMETER_NAME='FTP_LOG_FILE'

	SELECT PARAMETER_NAME, PARAMETER_VALUE
	FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	WHERE INTERFACE_NAME_CD='CLS'
	AND PARAMETER_NAME='FTP_COMMAND_EXE'
	
SELECT 'AND MAKE SURE THAT THIS BATCH FILE HAS THE RIGHT PATH TO WINSCP.EXE IN IT' AS READ_THIS_ENTIRE_INSTRUCTION2
	

