CREATE TABLE dbo.XX_UTIL_EDU_CODES
(
    PROJ_ABBRV_CD varchar(6) NOT NULL
)
go
IF OBJECT_ID('dbo.XX_UTIL_EDU_CODES') IS NOT NULL
    PRINT '<<< CREATED TABLE dbo.XX_UTIL_EDU_CODES >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE dbo.XX_UTIL_EDU_CODES >>>'
go
