-- TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_GENL_LAB_CAT] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_RATE_RETRO_TS_PREP_TEMP] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_RATE_RETRO_TS_PREP_ARC] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_RATE_RETRO_TS_PREP_ERRORS] TO imapsprd, imapsstg


-- Stored Procedures
--GRANT EXECUTE ON [dbo].[XX_CERIS_PROCESS_RETRO_RATE_SP] TO imapsprd, imapsstg
--GRANT EXECUTE ON [dbo].[XX_CERIS_RETRORATE_RUN_INTERFACE_SP] TO imapsprd, imapsstg

GRANT EXECUTE ON [dbo].[XX_RETRORATE_GET_PROCESSING_PARAMS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_ADD_NEW_REC_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_CHECK_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_PROCESS_CP_ERROR_LOG_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_PREPARE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_READY_CP_RUN_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_RUN_INTERFACE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_RETRORATE_VALIDATE_USR_CMD_LINE_SP] TO imapsprd, imapsstg






