
--DELTEK TABLES
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.AOPUTLAP_INP_HDR TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.AOPUTLAP_INP_DETL TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.AOPUTLJE_INP_TR TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.AOPUTLJE_INP_VEN TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.VEND TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.VEND_ADDR TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.DFLT_AP_ACCTS TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.DFLT_CASH_ACCTS TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.PROJ TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.GENL_UDEF TO imapsstg, imapsprd
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.ORG TO IMAPSSTG
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.UDEF_LBL TO imapsstg, imapsprd
GRANT SELECT, INSERT, UPDATE, DELETE ON IMAPS.DELTEK.ORG_ACCT TO IMAPSPRD, IMAPSSTG
GRANT SELECT, UPDATE, DELETE, INSERT ON IMAPS.DELTEK.ACCT TO IMAPSPRD, IMAPSSTG