-- TABLES
GRANT SELECT ON IMAPS.DELTEK.PROJ TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.CUST TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.RPT_REV_SUM TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.ORG TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.AR_HDR_HS TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.PROJ_REV_SETUP TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.GENL_UDEF TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.PROJ_MOD TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.DELTEK.PROJ_BILL_HS TO imapsprd, imapsstg

-- Defect 976 Begin

--GRANT SELECT ON IMAPS.DELTEK.RPT_PROJ_UNBILLED TO imapsprd, imapsstg
--GRANT SELECT ON IMAPS.DELTEK.REORG_ORG_LINK TO imapsprd, imapsstg
--GRANT SELECT ON IMAPS.DELTEK.REORG_STRUC TO imapsprd, imapsstg

GRANT SELECT ON IMAPS.Deltek.PROJ_RPT_PROJ TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.PROJ_RPT_ID TO imapsprd, imapsstg
-- Defect CP600000074 10/2007 Begin
-- GRANT SELECT ON IMAPS.Deltek.Z_BLPUBILL_RPT TO imapsprd, imapsstg
-- Defect CP600000074 10/2007 End

-- Defect 976 End

-- Defect CP600000074 10/2007 Begin

GRANT SELECT ON IMAPS.Deltek.PSR_FINAL_DATA TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.BILL_INVC_HDR_HS TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.BILL_SCHEDULE TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.OPEN_BILLING_DETL TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.ALLOC_APPLIC TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.POOL_RT_TABLE TO imapsprd, imapsstg
GRANT SELECT ON IMAPS.Deltek.GL_POST_SUM TO imapsprd, imapsstg

-- Defect CP600000074 10/2007 End
