-- TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_BLUEPAGES_HIST] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_CP_DFLT_TS_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_CP_EMPL_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_CP_EMPL_LAB_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_CP_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_FIWLR_DIV16_STATUS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_HIST] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_HIST_ARCHIVAL] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_HIST_ERROR_ARCHIVAL] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_PORT_NEW_ORGS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_RETRO_TS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_RETRO_TS_PREP] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_RETRO_TS_PREP_ERRORS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_RETRO_TS_PREP_ARCHIVAL] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CERIS_VALIDAT_ERRORS] TO imapsprd, imapsstg

-- Stored Procedures
GRANT EXECUTE ON [dbo].[XX_CERIS_ARCHIVE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_CHK_RESOURCES_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_GET_PROCESSING_PARAMS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_INSERT_CP_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_RETRIEVE_SOURCE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_RUN_INTERFACE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_UPDATE_CP_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_VALIDATE_PREPARE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_PROCESS_RETRO_SP] TO imapsprd, imapsstg
--GRANT EXECUTE ON [dbo].[XX_CERIS_PROCESS_RETRO_ORG_SP] TO imapsprd, imapsstg
--GRANT EXECUTE ON [dbo].[XX_CERIS_PROCESS_RETRO_GLC_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_PROCESS_RETRO_GLC_AND_ORG_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CERIS_READY_CP_RUN_SP] TO imapsprd, imapsstg