-- TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_CP_DFLT_TS_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_CP_EMPL_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_CP_EMPL_LAB_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_CP_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_FILE_STG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_FILE_STG1] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_FILE_STG_ARCHIVAL] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_RETRO_TS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_RETRO_TS_PREP] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_RETRO_TS_PREP_ERRORS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_TS_PREP_ERRORS_TMP] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_R22_CERIS_VALIDAT_ERRORS] TO imapsprd, imapsstg

-- Stored Procedures
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_ARCHIVE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_GET_PROCESSING_PARAMS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_INSERT_CP_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_LOAD_RETRO_TS_PREP_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_READY_CP_RUN_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_PROCESS_RETRO_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_RETRIEVE_SOURCE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_RUN_INTERFACE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_UPDATE_CP_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_VALIDATE_PREPARE_DATA_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_CERIS_RETRORATE_RUN_INTERFACE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_R22_EMP_MAP_SP] TO imapsprd, imapsstg