-- TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[AOPUTLAP_INP_DETL] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[AOPUTLAP_INP_HDR] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[AOPUTLAP_INP_LAB] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[AOPUTLJE_INP_TR] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[PROJ] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[ORG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[ACCT] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[ACCT_GRP_SETUP] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [DELTEK].[ORG_ACCT] TO imapsprd, imapsstg