-- TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CASH_RECPT_HDR] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CASH_RECPT_TRN] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_ACTIV_ARCH] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_ACTIV_ERRORS] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_ACTIVITY] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_CLOSED_INVOICES] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_OPEN_BALANCES] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_OPEN_BALANCES_ARCH] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_AR_CCIS_OPEN_REMARKS] TO imapsprd, imapsstg


-- Stored Procedures
GRANT EXECUTE ON [dbo].[XX_AR_CCIS_ARCHIVE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_AR_CCIS_LOAD_CASH_RECPTS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_AR_CCIS_LOAD_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_AR_CCIS_PROCESS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_AR_CCIS_VALIDATE_RECPTS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_AR_RUN_INBOUND_SP] TO imapsprd, imapsstg