-- TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CLS_DOWN] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CLS_DOWN_ACCT_MAPPING] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CLS_DOWN_ACCT_SERV_MAPPING] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CLS_DOWN_LOG] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CLS_DOWN_PROJ_INFO] TO imapsprd, imapsstg
GRANT SELECT, INSERT, UPDATE, DELETE ON [dbo].[XX_CLS_DOWN_SUMMARY] TO imapsprd, imapsstg


-- Stored Procedures
GRANT EXECUTE ON [dbo].[XX_GET_CUSTOMER_FOR_PROJECT_UF] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_VALIDATE_FIN_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_CREATE_LOG_RECORD_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_RUN_INTERFACE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_LOAD_STAGE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_VALIDATE_CMR_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_GET_TOTALS_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_CREATE_FLAT_FILE_SP] TO imapsprd, imapsstg
GRANT EXECUTE ON [dbo].[XX_CLS_DOWN_ARCHIVE_FILES_SP] TO imapsprd, imapsstg