ALTER TABLE dbo.CP_PLC_CODE ALTER COLUMN PROJECT_ID VARCHAR(4) NOT NULL
go

ALTER TABLE dbo.CP_PLC_CODE ALTER COLUMN PLC VARCHAR(6) NOT NULL
go

ALTER TABLE dbo.CP_PLC_CODE ADD CONSTRAINT CP_PLC_CODE_PK PRIMARY KEY (PROJECT_ID, PLC)
go