-- Reference BP&S Service Request No. DR1631

USE IMAPSStg
GO

ALTER TABLE dbo.XX_IMAPS_TS_PREP_CONFIG_ERRORS ADD [ROW_ID] [int] IDENTITY(1,1) NOT NULL
GO
ALTER TABLE dbo.XX_IMAPS_TS_PREP_CONFIG_ERRORS ADD [X_RECORD_NO] [int] NULL
GO
ALTER TABLE dbo.XX_IMAPS_TS_PREP_CONFIG_ERRORS ADD [FEEDBACK] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
ALTER TABLE dbo.XX_IMAPS_TS_PREP_CONFIG_ERRORS ADD [UPDATE_DT] [datetime] NOT NULL DEFAULT (getdate())
GO


UPDATE XX_IMAPS_TS_PREP_CONFIG_ERRORS
SET FEEDBACK=''
GO