-- SQL commands to process Feature 415

DROP TABLE dbo.XX_IMAPS_ET_IN_TMP
GO

-- Add NOT NULL column AMENDMENT_NUM; this action cannot be accomplished by an ALTER TABLE statement
CREATE TABLE [XX_IMAPS_ET_IN_TMP] (
	[EMP_SERIAL_NUM] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_YEAR] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_MONTH] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_DAY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[PROJ_ABBR] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[SAT_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SAT_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SUN_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SUN_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MON_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MON_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[TUE_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[TUE_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[WED_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[WED_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[THU_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[THU_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FRI_REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FRI_OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLC] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RECORD_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AMENDMENT_NUM] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL -- feature 415
) ON [PRIMARY]
GO


-- increase the size or length of column TOTAL_RECORDS from 66 to 68
ALTER TABLE dbo.XX_IMAPS_ET_FTR_IN_TMP ALTER COLUMN TOTAL_RECORDS CHAR(68) NOT NULL
GO



DROP TABLE dbo.XX_ET_DAILY_IN
GO

CREATE TABLE [XX_ET_DAILY_IN] (
	[ET_DAILY_IN_RECORD_NUM] [int] IDENTITY (1, 1) NOT NULL ,
	[STATUS_RECORD_NUM] [int] NOT NULL ,
	[EMP_SERIAL_NUM] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_YEAR] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_MONTH] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_DAY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_DATE] [datetime] NOT NULL ,
	[TS_WEEK_END_DATE] [datetime] NOT NULL ,
	[PROJ_ABBR] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLC] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RECORD_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AMENDMENT_NUM] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,  -- feature 415
	[CREATED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CREATED_DATE] [datetime] NOT NULL ,
	[MODIFIED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MODIFIED_DATE] [datetime] NULL ,
	CONSTRAINT [PK_XX_ET_DAILY_IN] PRIMARY KEY  CLUSTERED 
	(
		[ET_DAILY_IN_RECORD_NUM]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] ,
	CONSTRAINT [FK_XX_ET_DAILY_IN] FOREIGN KEY 
	(
		[STATUS_RECORD_NUM]
	) REFERENCES [XX_IMAPS_INT_STATUS] (
		[STATUS_RECORD_NUM]
	)
) ON [PRIMARY]
GO



DROP TABLE dbo.XX_ET_DAILY_IN_ARC
GO


CREATE TABLE [XX_ET_DAILY_IN_ARC] (
	[ET_DAILY_IN_ARC_NUM] [int] IDENTITY (1, 1) NOT NULL ,
	[STATUS_RECORD_NUM] [int] NOT NULL ,
	[EMP_SERIAL_NUM] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_YEAR] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_MONTH] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_DAY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TS_DATE] [datetime] NOT NULL ,
	[TS_WEEK_END_DATE] [datetime] NOT NULL ,
	[PROJ_ABBR] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[REG_TIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[OVERTIME] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLC] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RECORD_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AMENDMENT_NUM] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL , -- feature 415
	[CREATED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CREATED_DATE] [datetime] NOT NULL ,
	[MODIFIED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MODIFIED_DATE] [datetime] NULL ,
	CONSTRAINT [PK_XX_ET_DAILY_IN_ARC] PRIMARY KEY  CLUSTERED 
	(
		[ET_DAILY_IN_ARC_NUM]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] ,
	CONSTRAINT [FK_XX_ET_DAILY_IN_ARC] FOREIGN KEY 
	(
		[STATUS_RECORD_NUM]
	) REFERENCES [XX_IMAPS_INT_STATUS] (
		[STATUS_RECORD_NUM]
	)
) ON [PRIMARY]
GO
