/**************************************************************************************

--  USE THE FOLLOWING QUERY TO CHOOSE INVOICES YOU'D LIKE TO INCLUDE IN TEST
--  DELETING THEM FROM SENT TABLE WILL ALLOW THEM TO BE PROCESSED AGAIN
--  IF YOU USE AND SAVE THIS SQL SEPARTELY, BE SURE TO KEEP THE INVOICE NUMBERS UNPOPULATED IN THE
--  WHERE CLAUSE.  THAT WAY, IT WON'T DELETE THE ENTIRE TABLE.

****************************************************************************************/

-- csp invoices with $0 invoice amounts
DELETE
FROM IMAPSSTG.dbo.XX_SABRIX_INVOICE_SENT
WHERE INVC_ID IN ('IBM-0002478577','IBM-0002478174','IBM-0002476233','IBM-0002476062','IBM-0002475906','IBM-0002475552','IBM-0002473563','IBM-0002472647')


-- csp invoices with invoice amounts
DELETE
FROM IMAPSSTG.dbo.XX_SABRIX_INVOICE_SENT
WHERE INVC_ID IN ('IBM-0002478896','IBM-0002478895')


/**************************************************************************************

--  USE THE FOLLOWING QUERY TO CHOOSE INVOICES YOU'D LIKE TO INCLUDE IN TEST
--  DELETING THEM FROM SENT TABLE WILL ALLOW THEM TO BE PROCESSED AGAIN
--  IF YOU USE AND SAVE THIS SQL SEPARTELY, BE SURE TO KEEP THE INVOICE NUMBERS UNPOPULATED IN THE
--  WHERE CLAUSE.  THAT WAY, IT WON'T DELETE THE ENTIRE TABLE.

****************************************************************************************/
DELETE
FROM IMAPSSTG.dbo.XX_SABRIX_INVOICE_SENT
WHERE INVC_ID IN ('IBM-0002479274','IBM-0002479298','IBM-0002479304')


DELETE
FROM IMAPSSTG.dbo.XX_SABRIX_INVOICE_SENT
WHERE INVC_ID IN ('IBM-0002479111','IBM-0002479112','IBM-0002479114','IBM-0002479120','IBM-0002479121'  )


/**************************************************************************************

RESET THE JOB

****************************************************************************************/


-- BEFORE 
SELECT * FROM 
-- UPDATE
imapsstg.dbo.XX_IMAPS_INT_STATUS
-- SET STATUS_CODE = 'COMPLETED'
WHERE INTERFACE_NAME = 'SABRIX'
and STATUS_RECORD_NUM in 
(SELECT MAX(STATUS_RECORD_NUM) FROM imapsstg.dbo.XX_IMAPS_INT_STATUS 
  WHERE INTERFACE_NAME = 'SABRIX') 


--UPDATE 
--SELECT * FROM 
UPDATE
imapsstg.dbo.XX_IMAPS_INT_STATUS
SET STATUS_CODE = 'COMPLETED',
STATUS_DESCRIPTION = 'DEV RESET: RUN ENDED AT > ' + STATUS_DESCRIPTION
WHERE INTERFACE_NAME = 'SABRIX'
and STATUS_RECORD_NUM in 
(SELECT MAX(STATUS_RECORD_NUM) FROM imapsstg.dbo.XX_IMAPS_INT_STATUS 
  WHERE INTERFACE_NAME = 'SABRIX') 

SELECT 'XX_IMAPS_INT_STATUS TABLE UPDATED' AS UPDATE_STATUS
  
--AFTER   
SELECT * FROM 
-- UPDATE
imapsstg.dbo.XX_IMAPS_INT_STATUS
-- SET STATUS_CODE = 'COMPLETED'
WHERE INTERFACE_NAME = 'SABRIX'
and STATUS_RECORD_NUM in 
(SELECT MAX(STATUS_RECORD_NUM) FROM imapsstg.dbo.XX_IMAPS_INT_STATUS 
  WHERE INTERFACE_NAME = 'SABRIX') 
  
SELECT COUNT(*) FROM IMAPSSTG.dbo.XX_SABRIX_INVOICE_SENT
