
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
SET 
PARAMETER_VALUE = REPLACE(PARAMETER_VALUE, 'D:\','%DATA_DRIVE%')
WHERE 1=1 
AND CHARINDEX(':\', PARAMETER_VALUE)>0
AND INTERFACE_NAME_CD = 'CLS_R22'
-- AND PARAMETER_NAME = 'SUM_FILE'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
SET 
PARAMETER_VALUE = REPLACE(PARAMETER_VALUE, 'S:\','%DATA_DRIVE%')
WHERE 1=1 
AND CHARINDEX(':\', PARAMETER_VALUE)>0
AND INTERFACE_NAME_CD = 'CLS_R22'
-- AND PARAMETER_NAME = 'SUM_FILE'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
SET 
PARAMETER_VALUE = REPLACE(PARAMETER_VALUE, 'T:\','%DATA_DRIVE%')
WHERE 1=1 
AND CHARINDEX(':\', PARAMETER_VALUE)>0
AND INTERFACE_NAME_CD = 'CLS_R22'
-- AND PARAMETER_NAME = 'SUM_FILE'



UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
SET 
PARAMETER_VALUE = REPLACE(PARAMETER_VALUE, 'D:\','%DATA_DRIVE%')
WHERE 1=1 
AND CHARINDEX(':\', PARAMETER_VALUE)>0
AND INTERFACE_NAME_CD = 'UTIL'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
SET 
PARAMETER_VALUE = REPLACE(PARAMETER_VALUE, 'S:\','%DATA_DRIVE%')
WHERE 1=1 
AND CHARINDEX(':\', PARAMETER_VALUE)>0
AND INTERFACE_NAME_CD = 'UTIL'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
SET 
PARAMETER_VALUE = REPLACE(PARAMETER_VALUE, 'T:\','%DATA_DRIVE%')
WHERE 1=1 
AND CHARINDEX(':\', PARAMETER_VALUE)>0
AND INTERFACE_NAME_CD = 'UTIL'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'YA' WHERE PARAMETER_NAME = 'ORG_ID_W' AND INTERFACE_NAME_CD = 'CLS_R22'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'george.alvarez@us.ibm.com;hao.tong@us.ibm.com' WHERE PARAMETER_NAME = 'IN_DESTINATION_SYSOWNER' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\interfaces\PROCESS\CLS_R22\R22_CLSDOWNSUMMARY.txt' WHERE PARAMETER_NAME = 'SUM_FILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\INTERFACES\PROGRAMS\CLS_R22\R22_CLSDOWN.BAT' WHERE PARAMETER_NAME = 'JAVA_CMD' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_Data\interfaces\PROCESS\CLS_R22\' WHERE PARAMETER_NAME = 'PROCESS_DIR' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_Data\interfaces\ARCHIVE\CLS_R22\' WHERE PARAMETER_NAME = 'ARCH_DIR' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_Data\interfaces\LOGS\CLS_R22\' WHERE PARAMETER_NAME = 'ERROR_DIR' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'IMAR_TO_CLS.BIN' WHERE PARAMETER_NAME = 'FTP_DEST_999FILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'F156PARM.TXT' WHERE PARAMETER_NAME = 'FTP_DEST_PARMFILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Props\CLS_R22\CLS_R22_WINSCP.TXT' WHERE PARAMETER_NAME = 'FTP_COMMAND_FILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\logs\CLS_R22/R22_CLS_FTP_log.txt' WHERE PARAMETER_NAME = 'FTP_LOG_FILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_Data\Interfaces\Logs\CLS_R22\' WHERE PARAMETER_NAME = 'CMD_PARAM' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\Process\CLS_R22\' WHERE PARAMETER_NAME = 'FIL_DIR' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\INTERFACES\PROGRAMS\BATCH\WINSCP_FTP.BAT' WHERE PARAMETER_NAME = 'FTP_COMMAND_EXE' AND INTERFACE_NAME_CD = 'UTIL'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"250 Transfer completed"' WHERE PARAMETER_NAME = 'CLS_SEARCH_PHRASE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\INTERFACES\PROCESS\CLS_R22\R22_CLSDOWN.EBC' WHERE PARAMETER_NAME = 'CURRENT_FILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '10' WHERE PARAMETER_NAME = 'ELAPSED' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '2' WHERE PARAMETER_NAME = 'CLS_FTP_ADJUST' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '2014' WHERE PARAMETER_NAME = 'ACCT_YR' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '12' WHERE PARAMETER_NAME = 'ACCT_MO' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\LOGS\CLS_R22\' WHERE PARAMETER_NAME = 'JAVA_LOG_DIR' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"R22_clsdown,R22_clsdownparm,R22_clsdownsummary"' WHERE PARAMETER_NAME = 'CFF_FILES' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"2,0,0"' WHERE PARAMETER_NAME = 'SQL_TO_EBCDIC' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\PROCESS\CLS_R22\R22_CLSDOWNPARM.TXT' WHERE PARAMETER_NAME = 'PARMFILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'IMAR_TO_CLS_DOWN_SUMMARY.TXT' WHERE PARAMETER_NAME = 'FTP_DEST_SUMFILE' AND INTERFACE_NAME_CD = 'CLS_R22'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\PROCESS\CLS_R22\IMAR_TO_CLS_ASCII.TXT' WHERE PARAMETER_NAME = 'TEXTFILE' AND INTERFACE_NAME_CD = 'CLS_R22'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\PROGRAMS\BATCH\ISIT_CURRENT.BAT' WHERE PARAMETER_NAME = 'ISIT_CURRENT' AND INTERFACE_NAME_CD = 'UTIL'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\PROGRAMS\BATCH\FTP_CHK.BAT' WHERE PARAMETER_NAME = 'FTP_CHECK_EXE' AND INTERFACE_NAME_CD = 'UTIL'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\PROGRAMS\BATCH\DOIT_XST.BAT' WHERE PARAMETER_NAME = 'DOES_FILE_EXIST_BAT' AND INTERFACE_NAME_CD = 'UTIL'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '%DATA_DRIVE%IMAPS_DATA\Interfaces\PROGRAMS\BATCH\WINSCP_FTP.BAT' WHERE PARAMETER_NAME = 'FTP_EXE' AND INTERFACE_NAME_CD = 'UTIL'



-- DELETE CLS DUPLICATES
DELETE 
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE PARAMETER_ID IN 
(SELECT PID FROM 
(select PARAMETER_NAME, COUNT(*) AS CNT, MAX(PARAMETER_ID) AS PID
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD LIKE 'CLS_R22'
AND PARAMETER_NAME NOT LIKE 'XX_R22_CLS%'
GROUP BY PARAMETER_NAME) X
WHERE CNT > 1) 


SELECT * FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS 
WHERE 1=1 
--AND CHARINDEX('COUNTRY', PARAMETER_NAME)>0
AND INTERFACE_NAME_CD = 'CLS_R22'
-- AND PARAMETER_NAME = 'ENV'
-- AND CHARINDEX('DEV', PARAMETER_VALUE)>0

