USE [IMAPSSTG]
GO

-- Add a XX_LOOKUP_DETAIL record for IMAPS FDS Interface

DECLARE @order integer

SELECT @order = (MAX(PRESENTATION_ORDER) + 1) 
  FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL
 WHERE LOOKUP_DOMAIN_ID = 1

INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(1, 'FDS', 'IMAPSSTG FDS Interface', @order, SUSER_SNAME(), GETDATE())
GO

-- Add a XX_LOOKUP_DOMAIN record for FDS Interface control points

INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DOMAIN
   (LOOKUP_DOMAIN_DESC, DOMAIN_CONSTANT, CREATED_BY, CREATED_DATE)
   VALUES('IMAPSSTG FDS Interface Control Points', 'LD_FDS_INTER_CTRL_PT', SUSER_SNAME(), GETDATE())
GO

-- Add XX_LOOKUP_DETAIL records for IMAPSSTG FDS Interface control points

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-001', 'Load invoice data into summary staging table', 1, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-002', 'Validate and update CMR data', 2, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-003', 'Load invoice line data to detail staging table', 3, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-004', 'Create interface flat files', 4, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-005', 'Load SENT table with new invoices', 5, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-006', 'FTP CCS AR file', 6, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-007', 'FTP FDS files', 7, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-008', 'FTP GLIM files', 8, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-009', 'FTP CCS Billing file', 9, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO

DECLARE @domain_id integer
SELECT @domain_id = LOOKUP_DOMAIN_ID FROM IMAPSSTG.DBO.XX_LOOKUP_DOMAIN WHERE DOMAIN_CONSTANT = 'LD_FDS_INTER_CTRL_PT'
INSERT INTO IMAPSSTG.DBO.XX_LOOKUP_DETAIL VALUES(@domain_id, 'FDS-010', 'Email Control file', 10, SUSER_SNAME(), GETDATE(), NULL, NULL)
GO
