INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'UTIL')
, 'UTIL', 'PAD_CHAR','32',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)

