USE [IMAPSStg]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_XX_SABRIX_INV_OUT_DTL]') AND parent_object_id = OBJECT_ID(N'[dbo].[XX_SABRIX_INV_OUT_DTL]'))
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_DTL] DROP CONSTRAINT [FK_XX_SABRIX_INV_OUT_DTL]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_RTNGE_382F5661]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_DTL] DROP CONSTRAINT [DF_XX_SABRIX_RTNGE_382F5661]
END

GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INV_OUT_DTL]    Script Date: 08/14/2018 17:19:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XX_SABRIX_INV_OUT_DTL]') AND type in (N'U'))
DROP TABLE [dbo].[XX_SABRIX_INV_OUT_DTL]
GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INV_OUT_DTL]    Script Date: 08/14/2018 17:19:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[XX_SABRIX_INV_OUT_DTL](
	[CUST_ID] [varchar](12) NOT NULL,
	[PROJ_ID] [varchar](30) NOT NULL,
	[PROJ_ABBRV_CD] [varchar](6) NOT NULL,
	[INVC_ID] [varchar](15) NULL,
	[INVC_DT] [smalldatetime] NOT NULL,
	[INVC_LN] [int] IDENTITY(1,1) NOT NULL,
	[CLIN_ID] [varchar](10) NULL,
	[ACCT_ID] [varchar](12) NULL,
	[TRN_DESC] [varchar](30) NULL,
	[TS_DT] [smalldatetime] NULL,
	[BILL_RT_AMT] [decimal](10, 4) NULL,
	[BILLED_HRS] [decimal](14, 2) NULL,
	[RI_BILLABLE_CHG_CD] [varchar](4) NULL,
	[I_MACH_TYPE] [varchar](5) NULL,
	[M_PRODUCT_CODE] [varchar](8) NULL,
	[BILLED_AMT] [decimal](14, 2) NOT NULL,
	[RTNGE_AMT] [decimal](14, 2) NOT NULL,
	[ID] [varchar](12) NULL,
	[NAME] [varchar](25) NULL,
	[BILL_LAB_CAT_CD] [varchar](6) NULL,
	[BILL_LAB_CAT_DESC] [varchar](30) NULL,
	[BILL_FM_GRP_NO] [smallint] NOT NULL,
	[BILL_FM_GRP_LBL] [varchar](20) NOT NULL,
	[BILL_FM_LN_NO] [smallint] NOT NULL,
	[BILL_FM_LN_LBL] [varchar](20) NOT NULL,
	[CUM_BILLED_HRS] [decimal](14, 2) NULL,
	[CUM_BILLED_AMT] [decimal](14, 2) NULL,
	[TC_AGRMNT] [varchar](2) NULL,
	[TC_PROD_CATGRY] [varchar](2) NULL,
	[TC_TAX] [varchar](2) NULL,
	[TA_BASIC] [decimal](14, 2) NOT NULL,
	[RF_GSA_INDICATOR] [varchar](1) NULL,
	[SALES_TAX_AMT] [decimal](14, 2) NOT NULL,
	[STATE_SALES_TAX_AMT] [decimal](14, 2) NOT NULL,
	[COUNTY_SALES_TAX_AMT] [decimal](14, 2) NOT NULL,
	[CITY_SALES_TAX_AMT] [decimal](14, 2) NOT NULL,
	[SALES_TAX_CD] [varchar](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[INVC_LN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_DTL]  WITH CHECK ADD  CONSTRAINT [FK_XX_SABRIX_INV_OUT_DTL] FOREIGN KEY([INVC_ID])
REFERENCES [dbo].[XX_SABRIX_INV_OUT_SUM] ([INVC_ID])
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_DTL] CHECK CONSTRAINT [FK_XX_SABRIX_INV_OUT_DTL]
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_DTL] ADD  CONSTRAINT [DF_XX_SABRIX_RTNGE_382F5661]  DEFAULT ((0)) FOR [RTNGE_AMT]
GO


