USE [IMAPSStg]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_CREAT_0619A337]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG] DROP CONSTRAINT [DF_XX_SABRIX_CREAT_0619A337]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_CREAT_070DC770]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG] DROP CONSTRAINT [DF_XX_SABRIX_CREAT_070DC770]
END

GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG]    Script Date: 08/14/2018 17:30:10 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG]') AND type in (N'U'))
DROP TABLE [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG]
GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG]    Script Date: 08/14/2018 17:30:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG](
	[STATUS_RECORD_NUM] [int] NOT NULL,
	[CTRL_PT4_RUN_FLAG] [varchar](1) NULL,
	[TOTAL_INVCS] [int] NULL,
	[TOTAL_CCS] [decimal](14, 2) NULL,
	[TOTAL_FDS] [decimal](14, 2) NULL,
	[TOTAL_CSP] [decimal](14, 2) NULL,
	[CREATED_DT] [datetime] NOT NULL,
	[CREATED_BY] [varchar](20) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG] ADD  DEFAULT (getdate()) FOR [CREATED_DT]
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM_DTLS_STG] ADD  DEFAULT (suser_sname()) FOR [CREATED_BY]
GO


