USE [IMAPSStg]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_HR_BI_395884C4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] DROP CONSTRAINT [DF_XX_SABRIX_HR_BI_395884C4]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_HR_CU_3A4CA8FD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] DROP CONSTRAINT [DF_XX_SABRIX_HR_CU_3A4CA8FD]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_HR_CU_3B40CD36]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] DROP CONSTRAINT [DF_XX_SABRIX_HR_CU_3B40CD36]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_SABRIX_HR_EM_3C34F16F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] DROP CONSTRAINT [DF_XX_SABRIX_HR_EM_3C34F16F]
END

GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INV_OUT_SUM]    Script Date: 08/14/2018 17:24:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XX_SABRIX_INV_OUT_SUM]') AND type in (N'U'))
DROP TABLE [dbo].[XX_SABRIX_INV_OUT_SUM]
GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INV_OUT_SUM]    Script Date: 08/14/2018 17:24:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[XX_SABRIX_INV_OUT_SUM](
	[CUST_ID] [varchar](12) NOT NULL,
	[PROJ_ID] [varchar](30) NOT NULL,
	[INVC_ID] [varchar](15) NOT NULL,
	[INVC_DT] [smalldatetime] NOT NULL,
	[STATUS_FL] [varchar](1) NOT NULL,
	[STATUS_RECORD_NUM] [int] NOT NULL,
	[BILL_TYPE] [varchar](1) NOT NULL,
	[FY_CD] [varchar](6) NOT NULL,
	[PD_NO] [smallint] NOT NULL,
	[CUR_JUL_DT] [int] NOT NULL,
	[I_BO] [varchar](3) NOT NULL,
	[CUST_ADDR_DC] [varchar](10) NOT NULL,
	[PRIME_CONTR_ID] [varchar](20) NOT NULL,
	[CUST_PO_ID] [varchar](20) NOT NULL,
	[CUST_TERMS_DC] [varchar](15) NOT NULL,
	[I_ENTERPRISE] [varchar](7) NULL,
	[CUST_NAME] [varchar](40) NOT NULL,
	[I_NAPCODE] [varchar](3) NULL,
	[C_STD_IND_CLASS] [varchar](4) NULL,
	[C_INDUS] [varchar](2) NULL,
	[C_STATE] [varchar](2) NULL,
	[C_CNTY] [varchar](3) NULL,
	[C_CITY] [varchar](4) NULL,
	[TI_CMR_CUST_TYPE] [varchar](1) NULL,
	[C_FDS_CUST_TYPE] [varchar](1) NULL,
	[I_MKG_DIV] [varchar](2) NULL,
	[I_COLL_OFF] [varchar](3) NULL,
	[C_COLL_DIV] [varchar](2) NULL,
	[T_CUST_REF_1] [varchar](17) NULL,
	[INVC_AMT] [decimal](14, 2) NOT NULL,
	[SALES_TAX_AMT] [decimal](14, 2) NULL,
	[CSP_AMT] [decimal](14, 2) NULL,
	[CSP_TAX_AMT] [decimal](14, 2) NULL,
	[FDS_INV_AMT] [decimal](14, 2) NOT NULL,
	[FDS_SALES_TAX_AMT] [decimal](14, 2) NULL,
	[TI_SVC_BO] [varchar](3) NULL,
	[HR_BILL_RT_FL] [varchar](1) NOT NULL,
	[HR_CUM_FL] [varchar](1) NOT NULL,
	[HR_CUR_FL] [varchar](1) NOT NULL,
	[HR_EMPL_NAME_FL] [varchar](1) NOT NULL,
	[TC_CERTIFC_STATUS] [varchar](1) NULL,
	[TC_TAX_CLASS] [varchar](3) NULL,
	[F_OCL] [char](1) NULL,
	[DIVISION] [char](2) NULL,
 CONSTRAINT [PK_SABRIX_INV_OUT_SUM] UNIQUE NONCLUSTERED 
(
	[INVC_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] ADD  CONSTRAINT [DF_XX_SABRIX_HR_BI_395884C4]  DEFAULT ('N') FOR [HR_BILL_RT_FL]
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] ADD  CONSTRAINT [DF_XX_SABRIX_HR_CU_3A4CA8FD]  DEFAULT ('N') FOR [HR_CUM_FL]
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] ADD  CONSTRAINT [DF_XX_SABRIX_HR_CU_3B40CD36]  DEFAULT ('N') FOR [HR_CUR_FL]
GO

ALTER TABLE [dbo].[XX_SABRIX_INV_OUT_SUM] ADD  CONSTRAINT [DF_XX_SABRIX_HR_EM_3C34F16F]  DEFAULT ('N') FOR [HR_EMPL_NAME_FL]
GO


