USE [IMAPSStg]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_IMAPS_MODIF_1CC8C9BC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INVOICE_SENT] DROP CONSTRAINT [DF_XX_IMAPS_MODIF_1CC8C9BC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XX_IMAPS_TIME_1DBCEDF5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[XX_SABRIX_INVOICE_SENT] DROP CONSTRAINT [DF_XX_IMAPS_TIME_1DBCEDF5]
END

GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INVOICE_SENT]    Script Date: 08/14/2018 20:37:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XX_SABRIX_INVOICE_SENT]') AND type in (N'U'))
DROP TABLE [dbo].[XX_SABRIX_INVOICE_SENT]
GO

USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_SABRIX_INVOICE_SENT]    Script Date: 08/14/2018 20:37:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[XX_SABRIX_INVOICE_SENT](
	[CUST_ID] [varchar](12) NOT NULL,
	[PROJ_ID] [varchar](30) NOT NULL,
	[INVC_ID] [varchar](15) NOT NULL,
	[INVC_AMT] [decimal](14, 2) NOT NULL,
	[INVC_DT] [smalldatetime] NOT NULL,
	[STATUS_RECORD_NUM] [int] NOT NULL,
	[MODIFIED_BY] [varchar](20) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[DIVISION] [char](2) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[XX_SABRIX_INVOICE_SENT] ADD  CONSTRAINT [DF_XX_IMAPS_MODIF_1CC8C9BC]  DEFAULT (user_name()) FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[XX_SABRIX_INVOICE_SENT] ADD  CONSTRAINT [DF_XX_IMAPS_TIME_1DBCEDF5]  DEFAULT (getdate()) FOR [TIME_STAMP]
GO

-- WHEN CREATED, THIS TABLE ALWAYS NEEDS TO START WITH THE EXACT SAME RECORDS THAT ARE IN THE IMAPS INVOICE SENT TABLE
INSERT INTO IMAPSSTG.DBO.XX_SABRIX_INVOICE_SENT SELECT * FROM IMAPSSTG.DBO.XX_IMAPS_INVOICE_SENT


