UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = '15858'
WHERE PARAMETER_NAME = 'XX_SABRIX_INTERFACE_DTL_VW'

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = '17770'
WHERE PARAMETER_NAME = 'XX_SABRIX_INTERFACE_HDR_VW'