-- CR-10363 Replace FDS feed with CCS_02 feed

USE IMAPSstg

-- BEFORE
SELECT * FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL
 WHERE LOOKUP_DOMAIN_ID = 7
   ORDER BY PRESENTATION_ORDER

-- change email to 10
UPDATE dbo.XX_LOOKUP_DETAIL
   SET PRESENTATION_ORDER = 10,
	   APPLICATION_CODE = 'FDS/CCS-010',
       MODIFIED_BY = SUSER_SNAME(),
       MODIFIED_DATE = GETDATE()
 WHERE LOOKUP_DOMAIN_ID = 7
   AND APPLICATION_CODE = 'FDS/CCS-009'
   AND PRESENTATION_ORDER = 9
GO



-- add new CCS as 9
INSERT INTO dbo.XX_LOOKUP_DETAIL
   (LOOKUP_DOMAIN_ID, APPLICATION_CODE, LOOKUP_DESCRIPTION, PRESENTATION_ORDER, CREATED_BY, CREATED_DATE)
   VALUES(7, 'FDS/CCS-009', 'FTP flat file to CCS A/R', 9, SUSER_SNAME(), GETDATE())
GO


-- AFTER
SELECT * FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL
 WHERE LOOKUP_DOMAIN_ID = 7
   ORDER BY PRESENTATION_ORDER

