-- /*
--WHERE THE BATCH FILE TO RUN CFF IS LOCATED
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_EXE','D:\APPS_TO_COMPILE\CFF\CCS_02.BAT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHERE THE JAVA PROGRAM WILL PUT THE CCS_02 EBCDIC FILE; MUST MATCH FILE SPECIFIED IN BATCH FILE
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_JAVA_DATA_FILE','CCS_02_OUT.FIL',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHERE THE JAVA PROGRAM WILL PUT THE CCS_02 ASCII FILE; MUST MATCH JAVA DATA FILE PLUS EXTENSION ".TXT"
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_JAVA_TEXT_FILE','CCS_02_OUT_FIL.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHERE THE JAVA PROGRAM WILL PUT THE CCS_02 TRANSACTION FILE; MUST MATCH VALUE IN THE TRX.PROPERTIES FILE ".TXT"
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_TRX_FILE','CCS_02_TRX.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--SPECIFY CFF LOG FILE AND LOCATION
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_CFF_LOG_FILE','D:\APPS_TO_COMPILE\CFF\CFF_CCS_02.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--WHAT TO CALL FILE TO BE FTP'D; MUST MATCH FTP COMMANDS
-- PROD IS CCS.G.FMA0IMA note: CCS.G.FMA0IMA(+1) IN THE FTP COMMAND FILE; username is IMAPFTP
-- TEST IS CCS.G.FMA0IMA note: CCS.G.FMA0IMA(+1) IN THE FTP COMMAND FILE; username is PTCCS04
-- DEV IS kar12.imaps.ccs.test  note: kar12.imaps.ccs.test(+1) IN THE FTP COMMAND FILE
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_FTP_FILE','SLIT.PRE.FEEDER.CMFDS.INPUT.ORIG',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--CUSTOM COMMAND FILE FOR CCS_02
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_FTP_COMMAND_FILE','D:\IMAPS_DATA\NotShared\CCS_02_FTP_COMMANDS.txt',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--SPECIFY FTP LOG FILE AND LOCATION
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_FTP_LOG_FILE','D:\IMAPS_DATA\NotShared\CCS_02_FTP_LOG.TXT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

--SPECIFY FTP INI FILE AND LOCATION FOR FILE THAT CONTAINS FTP_CHECK SCRIPT SUCCESS PARAMETERS
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values (12,'FDS/CCS','CCS_02_FTP_INI_FILE','D:\IMAPS_DATA\NotShared\CCS_02_FTP.INI',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)
-- */
-- 10/3/2018
--SPECIFY FTP COMMAND LINE AND LOCATION
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
-- DEV TO SEND TO DEAN
values (12,'FDS/CCS','CCS_02_FTP_CMD','D:\APPS_TO_COMPILE\CFF\CCS_02_FTP.BAT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)
-- TEST TO CCS TEST BOX - BE SURE TO CHANGE LOCATION OF SCRIPT FILE
--values (12,'FDS/CCS','CCS_02_FTP_CMD','C:\Progra~2\WinSCP\WinSCP.com /script=d:\apps_to_compile\cff\winscp.txt',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)



/*
-- dev for now
update  imapsstg.dbo.XX_PROCESSING_PARAMETERS
set parameter_value = 'kar12.imaps.ccs.test'
where parameter_name = 'CCS_02_FTP_FILE'


Select * FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'FDS/CCS' AND
CHARINDEX('FDS', PARAMETER_NAME) > 0

SELECT *
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
 WHERE INTERFACE_NAME_CD = 'FDS/CCS'
   AND PARAMETER_NAME = 'FTP_DIR'
*/      
Select * FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'FDS/CCS' AND
CHARINDEX('CCS_02', PARAMETER_NAME) > 0