     
INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
	values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'FDS/CCS'),'FDS/CCS','GLIM_FTP_CMD','D:\IMAPS_Data\Interfaces\PROGRAMS\FDS\GLIM_ftp.bat',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)
   
   
   SELECT PARAMETER_NAME, PARAMETER_VALUE
     FROM dbo.XX_PROCESSING_PARAMETERS
    WHERE INTERFACE_NAME_CD = 'FDS/CCS'
      AND CHARINDEX('LIM_', PARAMETER_NAME) > 0     
      
      