DECLARE @MailTo                 varchar(300),
        @email_msg_text         varchar(3000),
        @email_msg_subject      varchar(100),
        @Server_Environment     varchar(20),
		@srn					INTEGER
		
	SELECT @Server_Environment = PARAMETER_VALUE
	FROM   IMAPSSTG.dbo.XX_PROCESSING_PARAMETERS
	WHERE  parameter_name = 'SERVER_ENVIRONMENT'
	
	SELECT @MailTo = PARAMETER_VALUE
	FROM   IMAPSSTG.dbo.XX_PROCESSING_PARAMETERS
	WHERE  parameter_name = 'C360 ERROR MAIL'

    SET @email_msg_subject =  @Server_Environment + ' Notification - C360 INTERFACE FAILURE '

	SET @email_msg_text = 'This message was generated by the IMAPS financial system resulting from execution of the C360 Inbound Interface.  The customer download failed.'
	
	SET @email_msg_text =	@email_msg_text + ' Please check the job log and/or job history for details.  Do not reply to this message. '

	INSERT INTO IMAPSSTG.dbo.XX_IMAPS_MAIL_OUT
   (MESSAGE_TEXT, MESSAGE_SUBJECT, MAIL_TO_ADDRESS, ATTACHMENTS, STATUS_RECORD_NUM)
   VALUES(@email_msg_text, @email_msg_subject, @MailTo, '',0)


PRINT 'FAILURE EMAIL SENT - REVIEW JOB LOGS FOR DETAIL'   

