USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'EXECUTIVE OFFICE OF THE PRESIDENT', N'Y', CAST(N'2020-12-08T13:32:02.277' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF AGRICULTURE', N'Y', CAST(N'2020-12-08T13:32:02.293' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF COMMERCE', N'Y', CAST(N'2020-12-08T13:32:02.370' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF DEFENSE (DOD)', N'Y', CAST(N'2020-12-08T13:32:02.403' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF EDUCATION', N'Y', CAST(N'2020-12-08T13:32:02.403' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF ENERGY (DOE)', N'Y', CAST(N'2020-12-08T13:32:02.420' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF HEALTH AND HUMAN SERVICES (HHS)', N'Y', CAST(N'2020-12-08T13:32:02.433' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF HOMELAND SECURITY (DHS)', N'Y', CAST(N'2020-12-08T13:32:02.620' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF HOUSING AND URBAN DEVELOPMENT (HUD)', N'Y', CAST(N'2020-12-08T13:32:02.637' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF THE INTERIOR', N'Y', CAST(N'2020-12-08T13:32:02.653' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF JUSTICE (DOJ)', N'Y', CAST(N'2020-12-08T13:32:02.653' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF LABOR (DOL)', N'Y', CAST(N'2020-12-08T13:32:02.683' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF STATE', N'Y', CAST(N'2020-12-08T13:32:02.700' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF TRANSPORTATION', N'Y', CAST(N'2020-12-08T13:32:02.747' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF THE TREASURY', N'Y', CAST(N'2020-12-08T13:32:02.763' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DEPARTMENT OF VETERANS AFFAIRS (VA)', N'Y', CAST(N'2020-12-08T13:32:02.763' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'INDEPENDENT AGENCY', N'Y', CAST(N'2020-12-08T13:32:02.777' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_DEPT] ([DEPT_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CLASSIFIED', N'Y', CAST(N'2020-12-08T13:32:02.777' AS DateTime), N'CPSUPERUSER', 1)
GO
