USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'BPA', N'Y', CAST(N'2020-12-08T13:32:14.583' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CPAF', N'Y', CAST(N'2020-12-08T13:32:14.583' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CPFF', N'Y', CAST(N'2020-12-08T13:32:14.600' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CPIF', N'Y', CAST(N'2020-12-08T13:32:14.600' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CR', N'Y', CAST(N'2020-12-08T13:32:14.613' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FFP', N'Y', CAST(N'2020-12-08T13:32:14.613' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FPAF', N'Y', CAST(N'2020-12-08T13:32:14.630' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FPIF', N'Y', CAST(N'2020-12-08T13:32:14.647' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FPLOE', N'Y', CAST(N'2020-12-08T13:32:14.647' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'IDIQ', N'Y', CAST(N'2020-12-08T13:32:14.660' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'LH', N'Y', CAST(N'2020-12-08T13:32:14.660' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'T&M', N'Y', CAST(N'2020-12-08T13:32:14.677' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_PRIME_CONTR_TYPE] ([PRIME_CONTR_TYPE], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'OTHER', N'Y', CAST(N'2020-12-08T13:32:14.693' AS DateTime), N'CPSUPERUSER', 1)
GO
