USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'0D2338', N'PATEL,BIMAL', N'Y', CAST(N'2020-12-15T15:58:57.217' AS DateTime), N'C-SD4H', 1)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'7D7316', N'KING,ARTHUR', N'Y', CAST(N'2020-12-15T15:58:57.217' AS DateTime), N'C-SD4H', 1)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'6A3407', N'CHANATRY,JOHN', N'Y', CAST(N'2021-01-11T16:18:58.287' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'766430', N'GIANNINY,KIMBERLY', N'Y', CAST(N'2021-01-11T17:12:25.147' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'040405', N'NOLAN,DAVID', N'Y', CAST(N'2021-01-11T17:12:25.147' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'7D1047', N'SEPUCH,DEBRA', N'Y', CAST(N'2021-01-11T17:12:25.147' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'739213', N'SHEEHAN,ROBERT', N'Y', CAST(N'2021-01-11T17:12:25.147' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'0D3708', N'WALSH,MARY', N'Y', CAST(N'2021-01-11T17:12:25.147' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'0A2342', N'WARUNEK-GIERYIC,LUCILLE', N'Y', CAST(N'2021-01-11T17:12:25.147' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'2A1322', N'O''MEARA-BYERS,KAREN', N'Y', CAST(N'2021-01-11T17:16:49.640' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'0D4696', N'WILSON,AMY', N'Y', CAST(N'2021-01-11T17:21:29.793' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'2J4191', N'DUNAY,RICARD', N'Y', CAST(N'2021-01-11T17:21:29.793' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'2J5798', N'FRIEDLANDER,GINA', N'Y', CAST(N'2021-01-11T17:21:29.793' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'0D3473', N'KELLEHER,MARGARET', N'Y', CAST(N'2021-01-11T17:21:29.793' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'7A2707', N'NARDONE,HENRY', N'Y', CAST(N'2021-01-11T17:21:29.793' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'987786', N'BURY,PAUL', N'Y', CAST(N'2021-01-11T18:57:07.360' AS DateTime), N'PBURY', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_NEGOTIATOR] ([CN_NEGOTIATOR], [CN_NEGOTIATOR_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'2A5941', N'ONG,CANDICE-NHI', N'Y', CAST(N'2021-01-11T18:59:46.797' AS DateTime), N'PBURY', 0)
GO
