USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_CN_MANAGER] ([CN_MANAGER], [CN_MANAGER_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'2A5941', N'ONG,CANDICE-NHI', N'Y', CAST(N'2020-12-15T15:59:06.937' AS DateTime), N'C-SD4H', 1)
GO
INSERT [DELTEK].[XT_LIST_CN_MANAGER] ([CN_MANAGER], [CN_MANAGER_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'987786', N'BURY,PAUL', N'Y', CAST(N'2020-12-15T15:59:06.933' AS DateTime), N'C-SD4H', 1)
GO
INSERT [DELTEK].[XT_LIST_CN_MANAGER] ([CN_MANAGER], [CN_MANAGER_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'6A3407', N'CHANATRY,JOHN', N'Y', CAST(N'2021-01-11T16:18:26.333' AS DateTime), N'CONG', 0)
GO
INSERT [DELTEK].[XT_LIST_CN_MANAGER] ([CN_MANAGER], [CN_MANAGER_NAME], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'0D4696', N'WILSON,AMY', N'Y', CAST(N'2021-01-11T17:21:55.593' AS DateTime), N'PBURY', 0)
GO
