USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_IBM_DIVISIONS] ([DIV_NO], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'16', 10, N'Y', CAST(N'2020-12-08T13:32:34.170' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_IBM_DIVISIONS] ([DIV_NO], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'12', 20, N'Y', CAST(N'2020-12-08T13:32:34.200' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_IBM_DIVISIONS] ([DIV_NO], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'1M - NIAS', 30, N'Y', CAST(N'2020-12-08T13:32:34.200' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_IBM_DIVISIONS] ([DIV_NO], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'OTHER', 40, N'Y', CAST(N'2020-12-08T13:32:34.233' AS DateTime), N'CPSUPERUSER', 1)
GO
