USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_ACO_POC] ([ACO_POC], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'SAME AS GOVT PROCUREMENT OFFICE', 10, N'Y', CAST(N'2020-12-08T13:32:49.820' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACO_POC] ([ACO_POC], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'DCMAE GARDEN CITY, 201 VARICK ST., NEW YORK, NY', 20, N'Y', CAST(N'2020-12-08T13:32:49.837' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACO_POC] ([ACO_POC], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'NISC', 30, N'Y', CAST(N'2020-12-08T13:32:49.853' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACO_POC] ([ACO_POC], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'OTHER', 40, N'Y', CAST(N'2020-12-08T13:32:49.853' AS DateTime), N'CPSUPERUSER', 1)
GO
