USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_SMALL_BUS_PLAN] ([SMALL_BUS_PLAN], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'NO', 10, N'Y', CAST(N'2020-12-08T13:33:09.370' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_SMALL_BUS_PLAN] ([SMALL_BUS_PLAN], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'INDIVIDUAL PLAN', 20, N'Y', CAST(N'2020-12-08T13:33:09.400' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_SMALL_BUS_PLAN] ([SMALL_BUS_PLAN], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CORPORATE PLAN', 30, N'Y', CAST(N'2020-12-08T13:33:09.417' AS DateTime), N'CPSUPERUSER', 1)
GO
