USE [IMAPS]
GO
INSERT [DELTEK].[XT_LIST_ACQ_TYPES] ([ACQ_TYPE], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FAR PART 12 (COMMERCIAL ITEM CONTRACT)', 20, N'Y', CAST(N'2020-12-08T13:33:09.430' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACQ_TYPES] ([ACQ_TYPE], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FAR PART 15', 30, N'Y', CAST(N'2020-12-08T13:33:09.447' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACQ_TYPES] ([ACQ_TYPE], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'FAR PART 12 & 15', 40, N'Y', CAST(N'2020-12-08T13:33:09.463' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACQ_TYPES] ([ACQ_TYPE], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'COMMERCIAL', 50, N'Y', CAST(N'2020-12-08T13:33:09.493' AS DateTime), N'CPSUPERUSER', 1)
GO
INSERT [DELTEK].[XT_LIST_ACQ_TYPES] ([ACQ_TYPE], [SEQ_NO], [SHOW_IN_LOOKUP], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'OTHER', 60, N'Y', CAST(N'2020-12-08T13:33:09.493' AS DateTime), N'CPSUPERUSER', 1)
GO
