USE [IMAPS]
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DFARS', N'Department of Defense Federal Acquisition Regulation Supplement', N'Y', N'S', N'DELTEK', CAST(N'2020-05-18T12:37:39.480' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NA', N'Not Applicable', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.787' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'GSA', N'General Services Administration (GSA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.850' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FARM', N'Farm Service Agency', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.850' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FOREST', N'Forest Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.863' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'RURAL', N'Rural Development', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.863' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CEN', N'Bureau of the Census', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.880' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NIST', N'National Institute of Standards & Technology (NIST)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.897' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NOAA', N'National Oceanic & Atmospheric Administration (NOAA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.897' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NTIS', N'National Technical Information Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.910' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'PTO', N'United States Patent & Trademark Office', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.910' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OSD', N'Office of the Secretary of Defense (OSD)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.927' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USAF', N'Air Force', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.943' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'ARMY', N'Army', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.960' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USMC', N'United States Marine Corps (USMC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.960' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NAVY', N'Navy', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.973' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DARPA', N'Defense Advanced Research Projects Agency (DARPA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.973' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DECA', N'Defense Commissary Agency', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:03.990' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DFAS', N'Defense Finance and Accounting Service (DFAS)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.003' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DISA', N'Defense Information Systems Agency (DISA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.003' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DIA', N'Defense Intelligence Agency (DIA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.020' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DLA', N'Defense Logistics Agency (DLA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.020' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DSCA', N'Defense Security Cooperation Agency (DSCA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.037' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'MDA', N'Missile Defense Agency (MDA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.037' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NGIA', N'National Geospatial-Intelligence Agency', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.050' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NSA', N'National Security Agency (NSA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.050' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'STUDENT', N'Federal Student Aid', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.067' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FOSSIL', N'Fossil Energy', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.083' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NNSA', N'National Nuclear Security Administration', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.100' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'WAPA', N'Western Area Power Administration', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.100' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'AHRQ', N'Agency for Healthcare Research and Quality (AHRQ)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.113' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CDC', N'Centers for Disease Control and Prevention (CDC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.113' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CMS', N'Centers for Medicare & Medicaid Services', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.130' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FDA', N'Food and Drug Administration (FDA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.130' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NIH', N'National Institutes of Health', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.147' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'PSC', N'Program Support Center', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.160' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FEMA', N'Federal Emergency Management Agency (FEMA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.177' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'TSA', N'Transportation Security Administration (TSA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.193' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CIS', N'U.S. Citizenship and Immigration Services (CIS)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.210' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USCG', N'U.S. Coast Guard (USCG)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.223' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'UCBP', N'U.S. Customs and Border Protection (CBP)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.240' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'ICE', N'U.S. Immigration and Customs Enforcement (ICE)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.253' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'GINNIE', N'Government National Mortgage Association (Ginnie Mae)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.270' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FBI', N'Federal Bureau of Investigation (FBI)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.287' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OSHA', N'Occupational Safety & Health Administration (OSHA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.317' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USFWS', N'Fish & Wildlife Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.333' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NPS', N'National Park Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.333' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'BPD', N'Bureau of Public Debt', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.350' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'IRS', N'Internal Revenue Service (IRS)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.350' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OCC', N'Office of the Comptroller of the Currency', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.363' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USM', N'United States Mint', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-19T13:48:43.200' AS DateTime), 778)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FAA', N'Federal Aviation Administration (FAA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.380' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FHWA', N'Federal Highway Administration', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.380' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FMCSA', N'Federal Motor Carrier Safety Administration', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.397' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'VHA', N'Veterans Health Administration', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.410' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'MWAA', N'Metropolitan Washington Airport Authority', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.410' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CIA', N'Central Intelligence Agency (CIA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.427' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CFT', N'Commodity Futures Trading Commission', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.427' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'EPA', N'Environmental Protection Agency (EPA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.443' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FCC', N'Federal Communications Commission (FCC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.443' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FDIC', N'Federal Deposit Insurance Corporation (FDIC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.460' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FRTIB', N'Federal Retirement Thrift Investment Board', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.460' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NASA', N'National Aeronautics and Space Administration (NASA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.473' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NSF', N'National Science Foundation (NSF)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.503' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OPM', N'Office of Personnel Management', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.520' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'ONCI', N'Office of the National Counterintelligence Executive', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.537' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'SEC', N'Securities and Exchange Commission (SEC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.550' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'SSA', N'Social Security Administration (SSA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.583' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'TVA', N'Tennessee Valley Authority', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.600' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USAID', N'United States Agency for International Development (USAID)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.613' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USPS', N'United States Postal Service (USPS)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.630' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FHA', N'Federal Housing Administration (FHA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.647' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FHFA', N'Federal Housing Finance Agency (FHFA)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.660' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'LOC', N'Library of Congress (LOC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.693' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'PBGC', N'Pension Benefit Guarantee Corporation (PBGC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.693' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USSEN', N'United States Senate', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T13:35:21.730' AS DateTime), 778)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USCOU', N'Administrative Office of US Courts (AOUSC)', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.723' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OTHER-G', N'Other - US Government', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.740' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OTHER-QO', N'Other - Quasi-Official', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.740' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'CLASS', N'Classified', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.753' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'MPO', N'Maryland Procurement Office', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.753' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OPO', N'Office of Procurement Operations', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.770' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FISCAL', N'Bureau of Fiscal Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.770' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'FERC', N'Federal Energy Regulatory Commission', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.787' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'WRLDB', N'World Bank Group', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.787' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'RRB', N'Railroad Retirement Board', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.800' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'MCC', N'Millennium Challenge Corporation', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.800' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NEXCOM', N'Navy Exchange Service Command', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.817' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USTC', N'United States Transportation Command', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.817' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'USSOCOM', N'United States Special Operations Command', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.833' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DCMA', N'Defense Contract Management Agency', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.850' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DCAA', N'Defense Contract Audit Agency', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.850' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'AAFES', N'Army & Air Force Exchange Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.863' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'WHS', N'Washington Headquarters Service', N'Y', N'U', N'DATACONS', CAST(N'2020-12-08T13:34:04.863' AS DateTime), 777)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NARA', N'National Archives and Records Administration', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T11:37:21.310' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'SPACE', N'United States Space Force', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T12:46:55.317' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'DHA', N'Defense Health Agency', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T13:09:35.497' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NCSA', N'National Center for Supercomputing Applications', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T12:56:49.060' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'MARINES', N'US Marine Corps', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T12:59:55.670' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'COMPTROLLER', N'Office of the Comptroller of the Currency', N'N', N'U', N'C-PXGY', CAST(N'2021-02-21T13:29:08.697' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'NATO', N'North Atlantic Treaty Organization', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-21T13:44:11.940' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_AGENCIES] ([AGENCY_CD], [AGENCY_TITLE], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'COMMERCIAL', N'Not Govt Funded', N'Y', N'U', N'C-PXGY', CAST(N'2021-02-22T13:49:08.530' AS DateTime), 1)
GO
