USE [IMAPS]
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'VERBAL', N'Verbal', N'N', N'S', N'C-SD4J', CAST(N'2021-03-04T10:14:46.043' AS DateTime), 1, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'NTP', N'Notice to Proceed', N'N', N'S', N'C-SD4J', CAST(N'2021-03-04T10:14:46.043' AS DateTime), 1, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'AWARDED', N'Awarded', N'Y', N'S', N'DELTEK', CAST(N'2020-05-16T18:10:58.423' AS DateTime), 0, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'SWO', N'Stop Work Order', N'N', N'S', N'C-SD4J', CAST(N'2021-03-04T10:14:46.043' AS DateTime), 1, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'FURL', N'Furlough Notice', N'N', N'S', N'C-SD4J', CAST(N'2021-03-04T10:14:46.043' AS DateTime), 1, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'COMPLETED', N'POP Complete Awaiting Close Out', N'Y', N'S', N'DELTEK', CAST(N'2020-05-16T18:10:58.423' AS DateTime), 0, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'FBILL', N'Final Billing', N'N', N'S', N'C-SD4J', CAST(N'2021-03-04T10:14:46.043' AS DateTime), 1, N'Y')
GO
INSERT [DELTEK].[CT_CNTR_STATUS] ([CNTR_STATUS_CD], [CNTR_STATUS_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION], [INC_BACKLOG_FL]) VALUES (N'CLOSED', N'Close Out Complete', N'Y', N'S', N'C-SD4J', CAST(N'2021-03-11T09:56:20.077' AS DateTime), 1, N'Y')
GO
