USE [IMAPS]
GO
INSERT [DELTEK].[SEC_CLR_SETTINGS] ([HRCHY_NO], [SEC_CLR_CD], [SEC_CLR_DESC], [S_SEC_LVL_CD], [SCI_FL], [SAP_FL], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (1, N'TOPSEC', N'Top Secret', N'T', N'N', N'N', N'C-SD4H', CAST(N'2020-12-15T15:55:34.237' AS DateTime), 0)
GO
INSERT [DELTEK].[SEC_CLR_SETTINGS] ([HRCHY_NO], [SEC_CLR_CD], [SEC_CLR_DESC], [S_SEC_LVL_CD], [SCI_FL], [SAP_FL], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (2, N'SEC', N'Secret', N'S', N'N', N'N', N'C-SD4H', CAST(N'2020-12-15T15:55:52.680' AS DateTime), 0)
GO
INSERT [DELTEK].[SEC_CLR_SETTINGS] ([HRCHY_NO], [SEC_CLR_CD], [SEC_CLR_DESC], [S_SEC_LVL_CD], [SCI_FL], [SAP_FL], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (3, N'SCI', N'Sensitive Compartmented Info', N'C', N'Y', N'N', N'C-PXGY', CAST(N'2021-02-03T13:58:41.320' AS DateTime), 3)
GO
