USE [IMAPS]
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'BASE', N'Base', N'Y', N'S', N'C-PXGY', CAST(N'2020-12-14T16:48:49.877' AS DateTime), 5)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OY1', N'Option Year 1', N'N', N'S', N'C-PXGY', CAST(N'2020-12-14T16:48:49.880' AS DateTime), 3)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OY2', N'Option Year 2', N'N', N'S', N'C-PXGY', CAST(N'2020-12-14T16:48:49.880' AS DateTime), 3)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OY3', N'Option Year 3', N'N', N'S', N'C-PXGY', CAST(N'2020-12-14T16:48:49.880' AS DateTime), 3)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OY4', N'Option Year 4', N'N', N'S', N'C-PXGY', CAST(N'2020-12-14T16:48:49.880' AS DateTime), 3)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP5', N'Option 5', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T13:40:24.750' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP6', N'Option 6', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T13:40:24.767' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP7', N'Option 7', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T13:40:24.767' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP8', N'Option 8', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T13:40:24.767' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP9', N'Option 9', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T13:40:24.767' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP1', N'Option 1', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T15:37:46.287' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP2', N'Option 2', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T15:37:46.287' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP3', N'Option 3', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T15:37:46.287' AS DateTime), 0)
GO
INSERT [DELTEK].[CT_CNTR_DTTYPE] ([CNTR_DT_CD], [CNTR_DT_DESC], [SHOW_LOOKUP_FL], [S_SOURCE_CD], [MODIFIED_BY], [TIME_STAMP], [ROWVERSION]) VALUES (N'OP4', N'Option 4', N'Y', N'U', N'C-PXGY', CAST(N'2020-12-14T16:48:49.880' AS DateTime), 2)
GO
