USE [IMAPS]
GO
INSERT [DELTEK].[S_CNTR_CONTACTS] ([S_CONTACT_CD], [S_CONTACT_DESC], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'PO', N'Procurement Official ', CAST(N'2021-02-22T10:50:09.770' AS DateTime), N'C-PXGY', 1)
GO
INSERT [DELTEK].[S_CNTR_CONTACTS] ([S_CONTACT_CD], [S_CONTACT_DESC], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'PRIMECUST', N'Primary Customer', CAST(N'2020-05-16T18:11:55.870' AS DateTime), N'DELTEK', 0)
GO
INSERT [DELTEK].[S_CNTR_CONTACTS] ([S_CONTACT_CD], [S_CONTACT_DESC], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CO', N'Contracting Officer', CAST(N'2020-05-16T18:12:10.793' AS DateTime), N'DELTEK', 0)
GO
INSERT [DELTEK].[S_CNTR_CONTACTS] ([S_CONTACT_CD], [S_CONTACT_DESC], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'CS', N'Contracting Specialist', CAST(N'2020-12-08T13:32:49.900' AS DateTime), N'CPSUPERUSER', 0)
GO
INSERT [DELTEK].[S_CNTR_CONTACTS] ([S_CONTACT_CD], [S_CONTACT_DESC], [TIME_STAMP], [MODIFIED_BY], [ROWVERSION]) VALUES (N'PRIMEADMIN', N'Prime Contractor Administrator', CAST(N'2020-12-08T13:32:49.930' AS DateTime), N'CPSUPERUSER', 0)
GO
