use imapsstg

TRUNCATE TABLE XX_CERIS_DIV16_STATUS

DECLARE CERIS_DATE CURSOR FAST_FORWARD FOR
SELECT
DISTINCT CREATE_DATE
FROM ETIME_RPT..CFRPTADM.IBM_CERIS_HIST
--WHERE CREATE_DATE >= '2005-01-01 00:00:00.000'
ORDER BY CREATE_DATE 

DECLARE @CERIS_DATE datetime
DECLARE @CURRENT_TIMESTAMP datetime

OPEN CERIS_DATE

FETCH CERIS_DATE INTO @CERIS_DATE

WHILE (@@FETCH_STATUS=0)
BEGIN
	
	SELECT @CURRENT_TIMESTAMP = @CERIS_DATE

	
	--LOAD DIVISION STATUS FROM CURRENT WEEK CERIS TABLE (populated and maintained by ETIME)
	INSERT INTO XX_CERIS_DIV16_STATUS
	(EMPL_ID, DIVISION, DIVISION_START_DT,
	 DIVISION_FROM, CREATED_BY, CREATION_DT)
	SELECT 
	 EMPLID, DIVISION, DIVISION_STRT_DATE, 
	 DIVISION_FROM, SUSER_SNAME(), @CURRENT_TIMESTAMP
	FROM ETIME_RPT..CFRPTADM.IBM_CERIS_HIST
	WHERE CREATE_DATE = @CERIS_DATE
	AND DIVISION_STRT_DATE IS NOT NULL

	--DELETE BORING OLD DUPLICATE CURRENT RECORDS
	DELETE XX_CERIS_DIV16_STATUS
	FROM XX_CERIS_DIV16_STATUS div
	WHERE 
	div.CREATION_DT = @CURRENT_TIMESTAMP
	AND
	1 <
	(SELECT COUNT(1) FROM XX_CERIS_DIV16_STATUS 
	 WHERE 
	 EMPL_ID = div.EMPL_ID 
	 AND DIVISION = div.DIVISION
	 AND DIVISION_START_DT = div.DIVISION_START_DT
	 AND ISNULL(DIVISION_FROM, '') = ISNULL(div.DIVISION_FROM, '')
	 )

	FETCH CERIS_DATE INTO @CERIS_DATE
END


CLOSE CERIS_DATE
DEALLOCATE CERIS_DATE



--LOAD THIS WEEK'S CERIS FILE

SELECT @CURRENT_TIMESTAMP = CURRENT_TIMESTAMP

--LOAD DIVISION STATUS FROM CURRENT WEEK CERIS TABLE (populated and maintained by ETIME)
INSERT INTO XX_CERIS_DIV16_STATUS
(EMPL_ID, DIVISION, DIVISION_START_DT,
	 DIVISION_FROM, CREATED_BY, CREATION_DT)
SELECT 
	EMPLID, DIVISION, DIVISION_STRT_DATE,
	DIVISION_FROM, SUSER_SNAME(), @CURRENT_TIMESTAMP
FROM ETIME_RPT..CFRPTADM.IBM_CERIS
WHERE DIVISION_STRT_DATE IS NOT NULL


--DELETE BORING OLD DUPLICATE CURRENT RECORDS
DELETE XX_CERIS_DIV16_STATUS
FROM XX_CERIS_DIV16_STATUS div
WHERE 
div.CREATION_DT = @CURRENT_TIMESTAMP
AND
1 <
(SELECT COUNT(1) FROM XX_CERIS_DIV16_STATUS 
 WHERE 
 EMPL_ID = div.EMPL_ID 
 AND DIVISION = div.DIVISION
 AND DIVISION_START_DT = div.DIVISION_START_DT
 AND ISNULL(DIVISION_FROM, '') = ISNULL(div.DIVISION_FROM, '')
 )

--INSERT UKNOWN RECORD FOR EMPLOYEES WHO WERE IN DIV16, 
--BUT FELL OFF THE FILE FOR SOME REASON
INSERT INTO XX_CERIS_DIV16_STATUS
(EMPL_ID, DIVISION, DIVISION_START_DT,
	 DIVISION_FROM, CREATED_BY, CREATION_DT)
SELECT 
	EMPL_ID, '??', @CURRENT_TIMESTAMP,
	'??', SUSER_SNAME(), @CURRENT_TIMESTAMP
FROM XX_CERIS_DIV16_STATUS div
WHERE 
CREATION_DT = (SELECT MAX(CREATION_DT) FROM XX_CERIS_DIV16_STATUS WHERE EMPL_ID = div.EMPL_ID)
AND
DIVISION = '16'
AND 
0 =
(SELECT COUNT(1) FROM ETIME_RPT..CFRPTADM.IBM_CERIS WHERE EMPLID = div.EMPL_ID)

