/*
select * from XX_ET_EXCLUDE_PROJECTS
*/

insert into XX_ET_EXCLUDE_PROJECTS
values ('D6S4',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('D6ST',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('D6IA',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DMS4',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DMST',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DMIA',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DPST',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DPS2',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DPS3',getdate(),'Y')

insert into XX_ET_EXCLUDE_PROJECTS
values ('DPIA',getdate(),'Y')

go
