/*
 * Defect 976 - 05/15/2006 - DB Object Changes
 *
 * Provide aged receivable and unbilled revenue data for 31-60 days, 61-90 days and more than 90 days.
 * Also, change the source of (1) PRACTICE_AREA and SERVICE_AREA from Costpoint tables PROJ and GENL_UDEF,
 * respectively, to PROJ_RPT_ID (via PROJ_RPT_PROJ) for both, and (2) UNBILLED_REVENUE from Costpoint
 * table RPT_PROJ_UNBILLED to Z_BLPUBILL_RPT.
 *
 * 07/14/2006: Do not include S_REV_FORMULA_CD and RETAINAGE_AMT in the final report. Add SERVICE_AREA_DESC.
 * Add column CONTRACT_NAME for level 1 contract name. Add column DATA_CATEGORY.
 */

DROP TABLE [XX_7KEYS_OUT_HDR]
GO

CREATE TABLE [XX_7KEYS_OUT_HDR] (
	[STATUS_RECORD_NUM] [int] NULL ,
	[ROW_NUM_TOTAL] [int] NULL ,
	[PERIOD_REVENUE_TOTAL] [decimal](14, 2) NULL ,
	[PERIOD_COST_TOTAL] [decimal](14, 2) NULL ,
	[YTD_REVENUE_TOTAL] [decimal](14, 2) NULL ,
	[YTD_COST_TOTAL] [decimal](14, 2) NULL ,
	[ITD_REVENUE_TOTAL] [decimal](14, 2) NULL ,
	[ITD_COST_TOTAL] [decimal](14, 2) NULL ,
	[ITD_FUNDING_TOTAL] [decimal](14, 2) NULL ,
	[UNBILLED_REVENUE_TOTAL] [decimal](14, 2) NULL ,
        [UNBILLED_REVENUE_31TO60DAYS_TOTAL] [decimal](14, 2) NULL ,
        [UNBILLED_REVENUE_61TO90DAYS_TOTAL] [decimal](14, 2) NULL ,
        [UNBILLED_REVENUE_OVER90DAYS_TOTAL] [decimal](14, 2) NULL ,
	[AGED_BILL_AMT_TOTAL] [decimal](14, 2) NULL ,
	[AGED_RECEIVABLE_31TO60DAYS_TOTAL] [decimal](14, 2) NULL ,
	[AGED_RECEIVABLE_61TO90DAYS_TOTAL] [decimal](14, 2) NULL ,
	[AGED_RECEIVABLE_OVER90DAYS_TOTAL] [decimal](14, 2) NULL ,
	[BILLED_AMT_TOTAL] [decimal](14, 2) NULL ,
	CONSTRAINT [FK_XX_7KEYS_OUT_HDR] FOREIGN KEY 
	(
		[STATUS_RECORD_NUM]
	) REFERENCES [XX_IMAPS_INT_STATUS] (
		[STATUS_RECORD_NUM]
	)
) ON [PRIMARY]
GO


DROP TABLE [XX_7KEYS_OUT_DETAIL]
GO

CREATE TABLE [XX_7KEYS_OUT_DETAIL] (
	[ROW_NUM] [int] IDENTITY (1, 1) NOT NULL ,
	[STATUS_RECORD_NUM] [int] NULL ,
	[PROJ_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DATA_CATEGORY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CONTRACT_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJ_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PRIME_CONTR_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LVL_NO] [smallint] NULL ,
	[L1_PROJ_SEG_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[L2_PROJ_SEG_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[L3_PROJ_SEG_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJ_MGR_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJ_EXECUTIVE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FINANCIAL_MANAGER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IBM_OPP_NUM_SIEBEL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CONTRACT_TYPE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SERVICE_AREA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SERVICE_AREA_DESC] [varchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PRACTICE_AREA] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MI0405_INDICATOR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[INDUSTRY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[INDUSTRY_NAME] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[KEY_ACCOUNT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[KEY_ACCOUNT_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[GROSS_PROFIT_MARGIN] [decimal](14, 4) NULL ,
	[CUST_LONG_NAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[S_REV_FORMULA_CD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_REVENUE] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___PERIO__7CD0301F] DEFAULT (0),
	[PERIOD_COST] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___PERIO__7DC45458] DEFAULT (0),
	[PERIOD_PROFIT] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___PERIO__7EB87891] DEFAULT (0),
	[YTD_REVENUE] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___YTD_R__7FAC9CCA] DEFAULT (0),
	[YTD_COST] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___YTD_C__00A0C103] DEFAULT (0),
	[YTD_PROFIT] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___YTD_P__0194E53C] DEFAULT (0),
	[ITD_REVENUE] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___ITD_R__02890975] DEFAULT (0),
	[ITD_COST] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___ITD_C__037D2DAE] DEFAULT (0),
	[ITD_PROFIT] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___ITD_P__047151E7] DEFAULT (0),
	[ITD_VALUE] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___ITD_V__05657620] DEFAULT (0),
	[ITD_FUNDING] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___ITD_F__06599A59] DEFAULT (0),
	[UNBILLED_REVENUE] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___UNBIL__0841E2CB] DEFAULT (0),
	[UNBILLED_REVENUE_31TO60DAYS] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___UNBIL__292EA0A1] DEFAULT (0),
	[UNBILLED_REVENUE_61TO90DAYS] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___UNBIL__2A22C4DA] DEFAULT (0),
	[UNBILLED_REVENUE_OVER90DAYS] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___UNBIL__2B16E913] DEFAULT (0),
	[AGED_BILL_AMT] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___AGED___09360704] DEFAULT (0),
	[AGED_RECEIVABLE_31TO60DAYS] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___AGED___2CFF3185] DEFAULT (0),
	[AGED_RECEIVABLE_61TO90DAYS] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___AGED___2DF355BE] DEFAULT (0),
	[AGED_RECEIVABLE_OVER90DAYS] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___AGED___2EE779F7] DEFAULT (0),
	[BILLED_AMT] [decimal](14, 2) NULL CONSTRAINT [DF__XX_7KEYS___BILLE__0A2A2B3D] DEFAULT (0),
	[MOD_NUM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_OF_PERFORMANCE_START_DT] [datetime] NULL ,
	[PERIOD_OF_PERFORMANCE_END_DT] [datetime] NULL ,
	[CREATED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CREATED_DT] [datetime] NOT NULL ,
	[MODIFIED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MODIFIED_DT] [datetime] NULL ,
	CONSTRAINT [FK_XX_7KEYS_OUT_DETAIL] FOREIGN KEY 
	(
		[STATUS_RECORD_NUM]
	) REFERENCES [XX_IMAPS_INT_STATUS] (
		[STATUS_RECORD_NUM]
	)
) ON [PRIMARY]
GO


DROP TABLE [XX_7KEYS_OUT_HDR_TEMP]
GO

CREATE TABLE [XX_7KEYS_OUT_HDR_TEMP] (
	[ROW_NUM_TOTAL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_REVENUE_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_COST_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[YTD_REVENUE_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[YTD_COST_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_REVENUE_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_COST_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_FUNDING_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_31TO60DAYS_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_61TO90DAYS_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_OVER90DAYS_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_BILL_AMT_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_RECEIVABLE_31TO60DAYS_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_RECEIVABLE_61TO90DAYS_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_RECEIVABLE_OVER90DAYS_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BILLED_AMT_TOTAL] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO


DROP TABLE [XX_7KEYS_OUT_DETAIL_TEMP]
GO

CREATE TABLE [XX_7KEYS_OUT_DETAIL_TEMP] (
	[PROJ_ID] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DATA_CATEGORY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CONTRACT_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJ_NAME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PRIME_CONTR_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJ_MGR_NAME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PROJ_EXECUTIVE] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FINANCIAL_MANAGER] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IBM_OPP_NUM_SIEBEL] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CONTRACT_TYPE] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SERVICE_AREA] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SERVICE_AREA_DESC] [varchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PRACTICE_AREA] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MI0405_INDICATOR] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[INDUSTRY] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[INDUSTRY_NAME] [char] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[KEY_ACCOUNT] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[KEY_ACCOUNT_NAME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[GROSS_PROFIT_MARGIN] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CUST_LONG_NAME] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_REVENUE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_COST] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_PROFIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[YTD_REVENUE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[YTD_COST] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[YTD_PROFIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_REVENUE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_COST] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_PROFIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_VALUE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITD_FUNDING] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_31TO60DAYS] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_61TO90DAYS] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[UNBILLED_REVENUE_OVER90DAYS] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_BILL_AMT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_RECEIVABLE_31TO60DAYS] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_RECEIVABLE_61TO90DAYS] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AGED_RECEIVABLE_OVER90DAYS] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BILLED_AMT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MOD_NUM] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_OF_PERFORMANCE_START_DT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PERIOD_OF_PERFORMANCE_END_DT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO
