ALTER TABLE dbo.XX_FIWLR_USDET_V3
	ADD [IDENT_REC_NO] [int] IDENTITY (1, 1) NOT NULL 
GO
ALTER TABLE dbo.XX_FIWLR_USDET_ARCHIVE
	ADD [IDENT_REC_NO] [int] NULL 
GO
ALTER TABLE dbo.XX_FIWLR_USDET_ARCHIVE
	ADD [CP_HDR_NO][int] NULL 
GO
ALTER TABLE dbo.XX_FIWLR_USDET_ARCHIVE
	ADD [CP_LN_NO] [int] NULL 
GO
ALTER TABLE dbo.XX_FIWLR_USDET_ARCHIVE
	ADD [FY_CD][varchar](6) NULL 
GO
ALTER TABLE dbo.XX_FIWLR_USDET_ARCHIVE
	ADD [PD_NO][smallint] NULL 
GO
ALTER TABLE dbo.XX_FIWLR_USDET_ARCHIVE
	ADD [SUB_PD_NO][smallint] NULL 
GO