USE [IMAPSStg]
GO

/****** Object:  View [dbo].[XX_FDS_INVOICE_REVERSAL_DETAIL_VW]    Script Date: 11/17/2022 2:07:17 PM ******/
DROP VIEW [dbo].[XX_FDS_INVOICE_REVERSAL_DETAIL_VW]
GO

/****** Object:  View [dbo].[XX_FDS_INVOICE_REVERSAL_DETAIL_VW]    Script Date: 11/17/2022 2:07:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO

CREATE VIEW [dbo].[XX_FDS_INVOICE_REVERSAL_DETAIL_VW]
AS

/* 
Used by FDS  to create REVERSAL FOR CLSDOWN

-- TO CHECK GRAND TOTAL
SELECT SUM(S.BILLINGS)-SUM(S.SALES_TAX_AMT)-SUM(S.CSP_AMT) AS REVERSE_TOT FROM FROM	IMAPSSTG.DBO.XX_FDS_INVOICE_REVERSAL_DETAIL_VW S

-- FDS QUERIES LIKE THIS TO CREATE REVERSAL

SELECT --INVOICE, 
		GETDATE() AS DT, S.RI_BILLABLE_CHG_CD,
		CUST_ADDR_DC, PRIME_CONTR_ID, 
		S.I_MACHINE_TYPE, S.M_PRODUCT_CODE, 
		--SUM(S.BILLINGS) AS TOTAL_BILLED,
		--SUM(S.OVER_CEILING) AS IGNORE_OVER_CEILING,
		--SUM(S.RTNGE_AMT) AS IGNORE_RTNGE,
		--SUM(S.SALES_TAX_AMT) AS SALES_TAX_AMT,
		--SUM(S.CSP_AMT) AS CSP_AMT,
		SUM(S.BILLINGS)-SUM(S.SALES_TAX_AMT)-SUM(S.CSP_AMT) AS REVERSE,
		PROJ_ABBRV_CD, DIVISION
FROM	IMAPSSTG.DBO.XX_FDS_INVOICE_REVERSAL_DETAIL_VW S
WHERE 1=1
		--CANNOT FILTER LIKE THIS HERE
		--AND S.BILLINGS <> S.SALES_TAX_AMT
		--AND S.ACCT_ID NOT IN ('48-79-08','49-79-08')
GROUP BY --INVOICE, 
		S.RI_BILLABLE_CHG_CD, S.I_MACHINE_TYPE, S.M_PRODUCT_CODE, CUST_ADDR_DC, PRIME_CONTR_ID, PROJ_ABBRV_CD, DIVISION 

		

****/



	WITH B AS (
		SELECT *, --* IS HERE BECAUSE QUERY BELOW NEEDS SOME B COLUMNS
          CASE WHEN ACCT_ID IN (
          SELECT PARAMETER_VALUE 
                    FROM IMAPSSTG.dbo.XX_PROCESSING_PARAMETERS 
                    WHERE PARAMETER_NAME = 'CSP_ACCT_ID' 
                      AND  INTERFACE_NAME_CD = 'FDS'
		  )     THEN 'Y'
                ELSE 'N'
		 END AS ACCT_IN_PARAMETERS
	FROM IMAPSSTG.dbo.XX_IMAPS_INV_OUT_DTL
 )
	SELECT 	GETDATE() DT,
		RIGHT(A.INVC_ID,7) invoice,B.ACCT_ID,
		b.RI_BILLABLE_CHG_CD,
		a.CUST_ADDR_DC, a.PRIME_CONTR_ID, 
		NULL AS I_MACHINE_TYPE, NULL AS M_PRODUCT_CODE,
		SUM(B.BILLED_AMT) AS BILLINGS,
		SUM(CASE 
		  WHEN PATINDEX('OVER %CEILING%',LTRIM(RTRIM(BILL_FM_GRP_LBL)))>0 THEN B.BILLED_AMT
		  ELSE 0
		END) AS OVER_CEILING,
		SUM(B.RTNGE_AMT) AS RTNGE_AMT,
		sum(B.sales_tax_amt) as sales_tax_amt,
		-- WITH QUERY USED FOR THIS
		SUM(CASE 
		  WHEN B.ACCT_IN_PARAMETERS = 'Y' THEN  B.BILLED_AMT
		  ELSE 0
		END) AS CSP_AMT, 
		b.PROJ_ABBRV_CD, a.DIVISION
		FROM 
		IMAPSSTG.dbo.XX_IMAPS_INV_OUT_SUM a
		-- WITH QUERY B ABOVE IS REFERRED TO BY REFERENCE INSTEAD OF
		--INNER JOIN
		--IMAPSSTG.dbo.XX_IMAPS_INV_OUT_DTL b
		JOIN B ON
		(	a.CUST_ID = b.CUST_ID 
		AND 	a.PROJ_ID = b.PROJ_ID 
		AND	a.INVC_ID = b.INVC_ID
		AND	a.INVC_DT = b.INVC_DT
		)
		WHERE
		1=1
		AND
		A.STATUS_FL = 'P'
		AND
		--DR7644
		b.RI_BILLABLE_CHG_CD not in ('OSW','OHW')
		-- INCLUDE CSP AND SALES TAX AND THEN REMOVE THEM ABOVE FOR EASIER UNDERSTANDING				
		--AND
		--b.ACCT_ID NOT IN ('48-79-08','49-79-08')
		--(SELECT PARAMETER_VALUE FROM IMAPSSTG.dbo.XX_PROCESSING_PARAMETERS WHERE PARAMETER_NAME = 'CSP_ACCT_ID')
		--AND
		--b.BILLED_AMT <> b.SALES_TAX_AMT
		AND
		RIGHT(A.INVC_ID,7) in (SELECT LEFT(INVOICENUMBER,7) FROM IMAPSSTG.DBO.XX_GLIM_INTERFACE_ALL_VW group by invoicenumber)
		GROUP BY RIGHT(A.INVC_ID,7), B.ACCT_ID,
		a.CUST_ADDR_DC, b.RI_BILLABLE_CHG_CD, a.PRIME_CONTR_ID, b.PROJ_ABBRV_CD, a.DIVISION
		UNION
		/**** OSW REPORTS NO BILLABLE CHG_CD AND NO I_MACH_TYPE AND M_PROD_CODE ****/
		SELECT 	GETDATE() DT,
		RIGHT(A.INVC_ID,7) invoice, B.ACCT_ID,
		'NA',
		a.CUST_ADDR_DC, a.PRIME_CONTR_ID, 
		NULL AS M1, b.M_PRODUCT_CODE,
		SUM(B.BILLED_AMT) AS BILLINGS,
		SUM(CASE 
		  WHEN PATINDEX('OVER %CEILING%',LTRIM(RTRIM(BILL_FM_GRP_LBL)))>0 THEN B.BILLED_AMT
		  ELSE 0
		END) AS OVER_CEILING,
		SUM(B.RTNGE_AMT) AS RTNGE_AMT,
		sum(B.sales_tax_amt) as sales_tax_amt,
		-- WITH QUERY USED FOR THIS
		SUM(CASE 
		  WHEN B.ACCT_IN_PARAMETERS = 'Y' THEN  B.BILLED_AMT
		  ELSE 0
		END) AS CSP_AMT, 
		b.PROJ_ABBRV_CD, a.DIVISION
		FROM 
		IMAPSSTG.dbo.XX_IMAPS_INV_OUT_SUM a
		--INNER JOIN
		--IMAPSSTG.dbo.XX_IMAPS_INV_OUT_DTL b
		JOIN B ON
		(	a.CUST_ID = b.CUST_ID 
		AND 	a.PROJ_ID = b.PROJ_ID 
		AND	a.INVC_ID = b.INVC_ID
		AND	a.INVC_DT = b.INVC_DT
		)
		WHERE
		1=1
		AND
		A.STATUS_FL = 'P'
		AND
		--DR7644
		b.RI_BILLABLE_CHG_CD = 'OSW'
		-- INCLUDE CSP AND SALES TAX AND THEN REMOVE THEM ABOVE FOR EASIER UNDERSTANDING
		--AND
		--b.ACCT_ID NOT IN ('48-79-08','49-79-08')
		--(SELECT PARAMETER_VALUE FROM IMAPSSTG.dbo.XX_PROCESSING_PARAMETERS WHERE PARAMETER_NAME = 'CSP_ACCT_ID')
		--AND
		--b.BILLED_AMT <> b.SALES_TAX_AMT
		AND
		RIGHT(A.INVC_ID,7) in (SELECT LEFT(INVOICENUMBER,7) FROM IMAPSSTG.DBO.XX_GLIM_INTERFACE_ALL_VW group by invoicenumber)
		GROUP BY RIGHT(A.INVC_ID,7), B.ACCT_ID,
		a.CUST_ADDR_DC, b.RI_BILLABLE_CHG_CD, a.PRIME_CONTR_ID, b.PROJ_ABBRV_CD,b.M_PRODUCT_CODE, a.DIVISION
		UNION
		/**** OHW REPORTS NO BILLABLE CHG_CD AND I_MACH_TYPE AND NO M_PROD_CODE ****/
		SELECT 	GETDATE() DT, 
		RIGHT(A.INVC_ID,7) invoice, B.ACCT_ID,
		'NA',
		a.CUST_ADDR_DC, a.PRIME_CONTR_ID, 
		b.I_MACH_TYPE, NULL,
		SUM(B.BILLED_AMT) AS BILLINGS,
		SUM(CASE 
		  WHEN PATINDEX('OVER %CEILING%',LTRIM(RTRIM(BILL_FM_GRP_LBL)))>0 THEN B.BILLED_AMT
		  ELSE 0
		END) AS OVER_CEILING,
		SUM(B.RTNGE_AMT) AS RTNGE_AMT,
		sum(B.sales_tax_amt) as sales_tax_amt,
		-- WITH QUERY USED FOR THIS
		SUM(CASE 
		  WHEN B.ACCT_IN_PARAMETERS = 'Y' THEN  B.BILLED_AMT
		  ELSE 0
		END) AS CSP_AMT, 
		b.PROJ_ABBRV_CD, a.DIVISION
		FROM 
		IMAPSSTG.dbo.XX_IMAPS_INV_OUT_SUM a
		--INNER JOIN
		--IMAPSSTG.dbo.XX_IMAPS_INV_OUT_DTL b
		JOIN B ON
		(	a.CUST_ID = b.CUST_ID 
		AND 	a.PROJ_ID = b.PROJ_ID 
		AND	a.INVC_ID = b.INVC_ID
		AND	a.INVC_DT = b.INVC_DT
		)
		WHERE
		1=1
		AND
		A.STATUS_FL = 'P'
		AND
		--DR7644
		b.RI_BILLABLE_CHG_CD = 'OHW'
		-- INCLUDE CSP AND SALES TAX AND THEN REMOVE THEM ABOVE FOR EASIER UNDERSTANDING
		--AND
		--b.ACCT_ID NOT IN ('48-79-08','49-79-08')
		--(SELECT PARAMETER_VALUE FROM IMAPSSTG.dbo.XX_PROCESSING_PARAMETERS WHERE PARAMETER_NAME = 'CSP_ACCT_ID')
		--AND
		--b.BILLED_AMT <> b.SALES_TAX_AMT
		AND
		RIGHT(A.INVC_ID,7) in (SELECT LEFT(INVOICENUMBER,7) FROM IMAPSSTG.DBO.XX_GLIM_INTERFACE_ALL_VW group by invoicenumber)
		GROUP BY RIGHT(A.INVC_ID,7), B.ACCT_ID,
		a.CUST_ADDR_DC, b.RI_BILLABLE_CHG_CD, a.PRIME_CONTR_ID, b.PROJ_ABBRV_CD, a.DIVISION,b.I_MACH_TYPE

/****




-- UNCOMMENT TOP AND BOTTOM QUERY LINES TO CHECK TOTAL
--) CHECK_TOTAL

*****/		


GO


