USE [IMAPSStg]
GO

/****** Object:  View [dbo].[XX_GLIM_INTERFACE_OOB_VW]    Script Date: 8/5/2020 2:10:32 PM ******/
DROP VIEW [dbo].[XX_GLIM_INTERFACE_OOB_VW]
GO

/****** Object:  View [dbo].[XX_GLIM_INTERFACE_OOB_VW]    Script Date: 8/5/2020 2:10:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO

/* 
Used by CFF for CCS and Sabrix Interface

*/

CREATE VIEW [dbo].[XX_GLIM_INTERFACE_OOB_VW]
AS

SELECT INVC_ID, COUNT(*) AS CNT, SUM(INVC_TOT) AS TOT
--SELECT *
FROM 
(SELECT 'HDR' AS SOURCE, INVC_ID, '0' AS LN_NUM, INVC_AMT AS INVC_TOT
FROM IMAPSSTG.DBO.XX_IMAPS_INV_OUT_SUM
WHERE STATUS_FL <> 'E'
UNION
SELECT 'DTL',INVC_ID,INVC_LN,BILLED_AMT * -1
FROM IMAPSSTG.DBO.XX_IMAPS_INV_OUT_DTL
WHERE INVC_ID IN
(SELECT INVC_ID FROM IMAPSSTG.DBO.XX_IMAPS_INV_OUT_SUM WHERE STATUS_FL <> 'E')
)X
-- WHERE INVC_ID = 'IBM-0002604221'
GROUP BY INVC_ID
HAVING SUM(INVC_TOT)<> 0
--ORDER BY INVC_ID


GO


