
SELECT 'NUMBER OF CONTRACTS IN LOAD FILE'
select COUNT(*) FROM DELTEK.TMP_WK_CNTR_MASTER_LOAD;

SELECT 'NUMBER OF CONTRACTS LOADED'
SELECT COUNT(*) FROM DELTEK.CNTR_MASTER;

SELECT 'NUMBER OF CONTRACTS IN LOAD FILE BY CN_MANAGER'
SELECT XT_CN_MANAGER, COUNT(*) AS NUMBER_OF_CONTRACTS FROM DELTEK.TMP_WK_CNTR_MASTER_LOAD
GROUP BY XT_CN_MANAGER
ORDER BY XT_CN_MANAGER ASC;


SELECT 'NUMBER OF CONTRACTS LOADED BY CN_MANAGER'
SELECT CN_MANAGER, COUNT(*) AS NUMBER_OF_CONTRACTS FROM DELTEK.XT_CNTR_MASTER
GROUP BY CN_MANAGER
ORDER BY CN_MANAGER ASC;


SELECT 'NUMBER OF CONTRACTS BY CONTRACTING PARTY CD IN LOAD FILE'
SELECT CNTR_PARTY_CD, COUNT(*) AS NUMBER_OF_CONTRACTS FROM DELTEK.TMP_CONTACT_CP_AGENCY_DEPT
GROUP BY CNTR_PARTY_CD
ORDER BY CNTR_PARTY_CD ASC;

SELECT 'NUMBER OF CONTRACTS LOADED BY CONTRACTING PARTY'
SELECT PRIME_CONTRACTOR, COUNT(*) 
FROM DELTEK.CNTR_MASTER
GROUP BY PRIME_CONTRACTOR
ORDER BY PRIME_CONTRACTOR ASC;



