-- Created for CR-1082 10/25/2007

declare @int_name_id int 
select @int_name_id = LOOKUP_ID 
from dbo.XX_LOOKUP_DETAIL 
where APPLICATION_CODE = 'PCLAIM' 
INSERT INTO dbo.XX_PROCESSING_PARAMETERS 
   (INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE) 
  VALUES(@int_name_id,  'PCLAIM', 'CURRENT_MONTH_POSTING', 'NO', SUSER_SNAME(), GETDATE()) 
go 




