SELECT top 5 * FROM IMAPSSTG.DBO.XX_IMAPS_int_status

SET IDENTITY_INSERT IMAPSSTG.DBO.XX_IMAPS_INT_STATUS ON

INSERT INTO IMAPSSTG.DBO.XX_IMAPS_int_status (STATUS_RECORD_NUM,	INTERFACE_NAME,	INTERFACE_TYPE,	INTERFACE_SOURCE_SYSTEM,	INTERFACE_DEST_SYSTEM,	INTERFACE_FILE_NAME,	INTERFACE_SOURCE_OWNER,	INTERFACE_DEST_OWNER,	STATUS_CODE,	STATUS_DESCRIPTION,	RECORD_COUNT_TRAILER,	RECORD_COUNT_INITIAL,	RECORD_COUNT_SUCCESS,	RECORD_COUNT_ERROR,	CREATED_BY,	CREATED_DATE,	MODIFIED_BY,	MODIFIED_DATE,	AMOUNT_INPUT,	AMOUNT_PROCESSED,	AMOUNT_FAILED) 
VALUES(0,'UTIL','O','IMAPS','IMAPS','','OPERATIONS','OPERATIONS','MAILED','FOR GENERAL NOTIFICATION',NULL,NULL,NULL,NULL,SUSER_SNAME(),GETDATE(),NULL,NULL,NULL,NULL,NULL)

SET IDENTITY_INSERT IMAPSSTG.DBO.XX_IMAPS_int_status OFF

SELECT top 5 * FROM IMAPSSTG.DBO.XX_IMAPS_int_status