INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS')
, 'CLS', 'D43','38103000000',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS')
, 'CLS', 'D44','48101000000',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS')
, 'CLS', 'L23','38103000000',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS')
, 'CLS', 'L24','48101000000',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS')
, 'CLS', '4E3','34203000000',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
VALUES ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS')
, 'CLS', '4E4','44201000000',SUSER_SNAME(), GETDATE(),NULL,NULL,NULL)
