UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'george.alvarez@us.ibm.com;hao.tong@us.ibm.com' WHERE PARAMETER_NAME = 'IN_DESTINATION_SYSOWNER' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\interfaces\PROCESS\CLS\CLSDOWNSUMMARY.txt' WHERE PARAMETER_NAME = 'SUM_FILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\INTERFACES\PROGRAMS\CLS\CLSDOWN.BAT' WHERE PARAMETER_NAME = 'JAVA_CMD' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_Data\interfaces\PROCESS\cls\' WHERE PARAMETER_NAME = 'PROCESS_DIR' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_Data\interfaces\ARCHIVE\CLS\' WHERE PARAMETER_NAME = 'ARCH_DIR' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_Data\interfaces\ERRORS\CLS\' WHERE PARAMETER_NAME = 'ERROR_DIR' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'IMAPS_TO_CLS.BIN' WHERE PARAMETER_NAME = 'FTP_DEST_999FILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'F155PARM.TXT' WHERE PARAMETER_NAME = 'FTP_DEST_PARMFILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\Props\CLS\CLS_WINSCP.TXT' WHERE PARAMETER_NAME = 'FTP_COMMAND_FILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\Interfaces\logs\cls/CLS_FTP_log.txt' WHERE PARAMETER_NAME = 'FTP_LOG_FILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_Data\Interfaces\Logs\CLS\' WHERE PARAMETER_NAME = 'CMD_PARAM' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\Interfaces\Process\cls\' WHERE PARAMETER_NAME = 'FIL_DIR' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\INTERFACES\PROGRAMS\BATCH\WINSCP_FTP.BAT' WHERE PARAMETER_NAME = 'FTP_COMMAND_EXE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"250 Transfer completed"' WHERE PARAMETER_NAME = 'CLS_SEARCH_PHRASE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\INTERFACES\PROCESS\CLS\CLSDOWN.EBC' WHERE PARAMETER_NAME = 'CURRENT_FILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '10' WHERE PARAMETER_NAME = 'ELAPSED' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '2' WHERE PARAMETER_NAME = 'CLS_FTP_ADJUST' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '2014' WHERE PARAMETER_NAME = 'ACCT_YR' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '12' WHERE PARAMETER_NAME = 'ACCT_MO' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\Interfaces\LOGS\CLS\' WHERE PARAMETER_NAME = 'JAVA_LOG_DIR' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"clsdown,clsdownparm,clsdownsummary"' WHERE PARAMETER_NAME = 'CFF_FILES' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = '"2,0,0"' WHERE PARAMETER_NAME = 'SQL_TO_EBCDIC' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\Interfaces\PROCESS\CLS\CLSDOWNPARM.TXT' WHERE PARAMETER_NAME = 'PARMFILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'IMAPS_TO_CLS_DOWN_SUMMARY.TXT' WHERE PARAMETER_NAME = 'FTP_DEST_SUMFILE' AND INTERFACE_NAME_CD = 'CLS'
UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS SET PARAMETER_VALUE = 'T:\IMAPS_DATA\Interfaces\PROCESS\CLS\IMAPS_TO_CLS_ASCII.TXT' WHERE PARAMETER_NAME = 'TEXTFILE' AND INTERFACE_NAME_CD = 'CLS'
-- DELETE CLS DUPLICATES
DELETE 
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE PARAMETER_ID IN 
(SELECT PID FROM 
(select PARAMETER_NAME, COUNT(*) AS CNT, MAX(PARAMETER_ID) AS PID
FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD LIKE 'CLS'
AND PARAMETER_NAME NOT LIKE 'XX_CLS%'
GROUP BY PARAMETER_NAME) X
WHERE CNT > 1) 