/**** CHECK TO SEE IF IT GOT INSERTED CORRECTLY *****/
SELECT PARAMETER_NAME, PARAMETER_VALUE 
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'CLS'
AND PARAMETER_NAME IN ('DEFAULT_RPT_PROJ_ID', '16_BAL_SHT_DIVISION')
ORDER BY PARAMETER_ID DESC

-- two records should appear

/***** IF THEY DO EXIST, THEN MAKE SURE THEY HAVE THE RIGHT VALUES ******/

UPDATE imapsstg.dbo.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = 'DTOP.PYGX.0000.144F'
WHERE INTERFACE_NAME_CD = 'CLS'
AND PARAMETER_NAME = 'DEFAULT_RPT_PROJ_ID'

UPDATE imapsstg.dbo.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = '16'
WHERE INTERFACE_NAME_CD = 'CLS'
AND PARAMETER_NAME = '16_BAL_SHT_DIVISION'

/****** BUT IF THEY DON'T EXIST, THEN ADD THEM AS REQUIRED ******/

--ACCOUNT TO BE USED BY CLSDOWN WHEN UDEF_TEXT FOR REVENUE LEVEL CANNOT BE FOUND
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','DEFAULT_RPT_PROJ_ID','DTOP.PYGX.0000.144F',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- DEFAULT DIVISION FOR BALANCE SHEET ACCOUNTS
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','16_BAL_SHT_DIVISION','16',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)


/**** CHECK TO SEE IF IT GOT UPDATED/INSERTED CORRECTLY *****/
SELECT TOP 2 * 
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'CLS'
AND PARAMETER_NAME IN ('DEFAULT_RPT_PROJ_ID', '16_BAL_SHT_DIVISION')
ORDER BY PARAMETER_ID DESC
