
INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS VALUES (  
  (SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),
  'CLS',
  'JAVA_LOG_DIR',
  'T:\IMAPS_DATA\Interfaces\LOGS\CLS\', SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','CFF_FILES','clsdown,clsdownparm,clsdownsummary',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)


insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','SQL_TO_EBCDIC','2,0,0',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

select INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE from imapsstg.dbo.XX_PROCESSING_PARAMETERS
where parameter_name = 'JAVA_LOG_DIR'

select INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE from imapsstg.dbo.XX_PROCESSING_PARAMETERS
where parameter_name = 'SQL_TO_EBCDIC'

select INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE from imapsstg.dbo.XX_PROCESSING_PARAMETERS
where parameter_name = 'CFF_FILES'


