
INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS VALUES (  
  (SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),
  'CLS',
  'ACCT_MO',
  '08', SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)


INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS VALUES (  
  (SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),
  'CLS',
  'ACCT_YR',
  '2020', SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)




