/**** CHECK TO SEE IF IT GOT INSERTED CORRECTLY *****/
SELECT PARAMETER_NAME, PARAMETER_VALUE 
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE -- INTERFACE_NAME_CD = 'CLS'
PARAMETER_NAME IN ('ISIT_CURRENT', 'CURRENT_FILE', 'ELAPSED')
ORDER BY PARAMETER_ID DESC

-- THREE records should appear

/***** IF THEY DO EXIST, THEN MAKE SURE THEY HAVE THE RIGHT VALUES ******/

UPDATE imapsstg.dbo.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = 'D:\IMAPS_DATA\Interfaces\PROGRAMS\ISIT_CURRENT.BAT'
WHERE INTERFACE_NAME_CD = 'UTIL'
AND PARAMETER_NAME = 'ISIT_CURRENT'

UPDATE imapsstg.dbo.XX_PROCESSING_PARAMETERS
/*** THIS VALUE MUST MATCH THE OUTPUT VALUE IN THE PROPERTIES FILE ***/
SET PARAMETER_VALUE = 'D:\IMAPS_DATA\Interfaces\PROGRAMS\java\cff\output\cls\CLSDOWN.EBC'
WHERE INTERFACE_NAME_CD = 'CLS'
AND PARAMETER_NAME = 'CURRENT_FILE'

UPDATE imapsstg.dbo.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = '2'
WHERE INTERFACE_NAME_CD = 'CLS'
AND PARAMETER_NAME = 'ELAPSED'

/****** BUT IF THEY DON'T EXIST, THEN ADD THEM AS REQUIRED ******/

--BATCH UTILITY THAT CHECKS FOR FILE NAME AND HOW LONG AGO IT WAS CREATED
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'UTIL'),'UTIL','ISIT_CURRENT','D:\IMAPS_DATA\Interfaces\PROGRAMS\ISIT_CURRENT.BAT',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- TARGET FILE CREATED BY JAVA PROGRAM
/*** THIS VALUE MUST MATCH THE OUTPUT VALUE IN THE PROPERTIES FILE ***/
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','CURRENT_FILE','D:\IMAPS_DATA\Interfaces\PROGRAMS\java\cff\output\cls\CLSDOWN.EBC',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)

-- TARGET FILE ELAPSED TIME LIMIT
insert into imapsstg.dbo.XX_PROCESSING_PARAMETERS
values ((SELECT CAST(LOOKUP_ID AS VARCHAR(10)) FROM IMAPSSTG.DBO.XX_LOOKUP_DETAIL WHERE APPLICATION_CODE = 'CLS'),'CLS','ELAPSED','2',SUSER_SNAME(),GETDATE(),NULL,NULL,NULL)




/**** CHECK TO SEE IF IT GOT UPDATED/INSERTED CORRECTLY *****/
SELECT TOP 3 * 
FROM imapsstg.dbo.XX_PROCESSING_PARAMETERS
WHERE PARAMETER_NAME IN ('ISIT_CURRENT', 'CURRENT_FILE', 'ELAPSED')
ORDER BY PARAMETER_ID DESC
