-- this file should be run only once, and it should be the last file run after everything else is deployed

-- delete previous entries to eliminate duplicates

DELETE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE CHARINDEX('SEARCH PHRASE',PARAMETER_VALUE) > 0

DELETE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE CHARINDEX('FTP_ADJUST',PARAMETER_VALUE) > 0


DECLARE @FDS INT, 
		@CLS INT,
		@SABRIX INT

SELECT @CLS=INTERFACE_NAME_ID FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'CLS'

SELECT @FDS=INTERFACE_NAME_ID FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'FDS/CCS'

SELECT @SABRIX=INTERFACE_NAME_ID FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'SABRIX'


INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@FDS,'FDS/CCS','CCS_02_SEARCH_PHRASE','250 Transfer completed', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@FDS,'FDS/CCS','CCS_02_FTP_ADJUST','1', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@FDS,'FDS/CCS','GLIM_SEARCH_PHRASE','250 Transfer completed', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@FDS,'FDS/CCS','GLIM_FTP_ADJUST','2', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@FDS,'FDS/CCS','CCS_SEARCH_PHRASE','250 Transfer completed', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@FDS,'FDS/CCS','CCS_FTP_ADJUST','1', SUSER_SNAME(),GETDATE())


INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@CLS,'CLS','CLS_SEARCH_PHRASE','250 Transfer completed', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@CLS,'CLS','CLS_FTP_ADJUST','2', SUSER_SNAME(),GETDATE())


INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@SABRIX,'SABRIX','SABRIX_SEARCH_PHRASE','250 Transfer completed', SUSER_SNAME(),GETDATE())

INSERT INTO IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
(INTERFACE_NAME_ID, INTERFACE_NAME_CD, PARAMETER_NAME, PARAMETER_VALUE, CREATED_BY, CREATED_DATE)
VALUES (@SABRIX,'SABRIX','SABRIX_FTP_ADJUST','2', SUSER_SNAME(),GETDATE())

SELECT TOP 20 * FROM  IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE LEFT(CREATED_DATE,12) = LEFT(GETDATE(),12)

