SELECT 
-- TOP 5
* FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'CLS'
AND CHARINDEX('JAVA', PARAMETER_NAME)>0

UPDATE IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
SET PARAMETER_VALUE = 'D:\IMAPS_DATA\INTERFACES\PROGRAMS\CLS\CLSDOWN.BAT'
WHERE INTERFACE_NAME_CD = 'CLS'
AND CHARINDEX('JAVA', PARAMETER_VALUE)>0

SELECT 
-- TOP 5
* FROM IMAPSSTG.DBO.XX_PROCESSING_PARAMETERS
WHERE INTERFACE_NAME_CD = 'CLS'
AND CHARINDEX('JAVA', PARAMETER_NAME)>0

