USE [IMAPSStg]
GO

/****** Object:  Table [dbo].[XX_CERIS_DATA_STG]    Script Date: 03/22/2017 15:47:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [REC_TYPE] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SERIAL] [char](6) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [HIRE_DATE_EFF] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [HIRE_DATE_SRD] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SEP_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DEPT_MGR_SER_1] [char](6) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DEPT_MGR_NAME_LAST] [char](30) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DEPT_MGR_NAME_INIT] [char](2) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [JOB_FAMILY_1] [char](3) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [JOB_FAMILY_DATE_1] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [LEVEL_PREFIX_1] [char](2) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [LEVEL_SUFFIX_1] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [LVL_DATE_1] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DIVISION_1] [char](2) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DIVISION_2] [char](2) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DIV_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DEPT_PLUS_SFX] [char](4) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DEPT_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [DEPT_SUF_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EX_NE_OUT] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EXEMPT_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [POS_CODE_1] [char](4) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [JOB_TITLE] [char](30) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [POS_DATE_1] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EMPL_STAT_1ST] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EMPL_STAT_3RD] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EMPL_STAT3_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EMPL_STAT_2ND] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [EMPL_STAT_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [WORK_SCHD] [char](5) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [WORK_SCHD_DATE] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SET_ID] [char](2) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [LOC_WORK_1] [char](3) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [LOC_WORK_ST] [char](2) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [LOC_WORK_DTE_1] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [TBWKL_CITY] [char](24) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SALARY] [char](10) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SAL_CHG_DTE_1] [char](8) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SAL_RTE_CDE] [char](1) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SAL_BASE] [char](10) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [SAL_MO_OUT] [char](10) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [NAME_LAST_MIXED] [char](50) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [NAME_FIRST_MIXED] [char](50) NULL
   ALTER TABLE [dbo].[XX_CERIS_DATA_STG] ALTER COLUMN [NAME_INIT] [char](3) NULL



GO

SET ANSI_PADDING OFF
GO



