
DROP TABLE  IMAPSSTG.DBO.XX_R22_CLS_DOWN_EXP_RCVRY_MAPPING 

SELECT * INTO IMAPSSTG.DBO.XX_R22_CLS_DOWN_EXP_RCVRY_MAPPING 
FROM 
	(SELECT *
FROM IMAPSSTG.DBO.XX_R22_CLS_DOWN_ACCT_MAPPING
WHERE -- LEFT(IMAPS_ACCT_START,1) > '2'
IMAPS_ACCT_START > '41-01-60'
AND IMAPS_ACCT_END < '44-00-00' )mysrc


UPDATE IMAPSSTG.DBO.XX_R22_CLS_DOWN_EXP_RCVRY_MAPPING 
SET CLS_MAJOR = '700',
CLS_MINOR = '9817',
CLS_SUB_MINOR = '0000'

