USE [IMAPSStg]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[XX_R22_CLS_DOWN_ACCT_MEMO_MAPPING]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
   DROP TABLE [dbo].[XX_R22_CLS_DOWN_ACCT_MEMO_MAPPING]
GO

CREATE TABLE [dbo].[XX_R22_CLS_DOWN_ACCT_MEMO_MAPPING](
	[ROW_NUM]       [int] IDENTITY(1,1) NOT NULL,
	[IMAPS_ACCT]    [char](8) NOT NULL,
	[CLS_MAJOR]     [char](3) NOT NULL,
	[CLS_MINOR]     [char](4) NOT NULL,
	[CLS_SUB_MINOR] [char](4) NOT NULL,
	[CONTRACT]      [char](1) NULL,
	[CUSTOMER]      [char](1) NULL,
	[PROJECT]       [char](1) NULL,
	[MACHINE_TYPE]  [char](1) NULL,
	[PRODUCT_ID]    [char](1) NULL,
	[APPLY_BURDEN]  [char](1) NULL,
	[MULTIPLIER]    [smallint] NULL,
	[CREATED_BY]    [varchar](20) NULL,
	[CREATED_DATE]  [datetime] NULL,
	[MODIFIED_BY]   [varchar](20) NULL,
	[MODIFIED_DATE] [datetime] NULL,
 CONSTRAINT [PK_XX_R22_CLS_DOWN_ACCT_MEMO_MAPPING] PRIMARY KEY CLUSTERED 
(
	[ROW_NUM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
