CREATE TABLE dbo.XX_R22_IMAPS_ET_FTR_IN_TMP
(
    FOOTER_IND     char(6)  NOT NULL,
    FOOTER_DATE    char(10) NOT NULL,
    FOOTER_TIME    char(8)  NOT NULL,
    TOTAL_REG_TIME char(11) NOT NULL,
    TOTAL_OVERTIME char(11) NOT NULL,
    TOTAL_RECORDS  char(77) NOT NULL
)
go
IF OBJECT_ID('dbo.XX_R22_IMAPS_ET_FTR_IN_TMP') IS NOT NULL
    PRINT '<<< CREATED TABLE dbo.XX_R22_IMAPS_ET_FTR_IN_TMP >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE dbo.XX_R22_IMAPS_ET_FTR_IN_TMP >>>'
go
