



	--0.  MARK RECORDS THAT WERE SUCCESSFULLY IMPORTED
	DECLARE @NEW_STATUS_RECORD_NUM int
	SELECT @NEW_STATUS_RECORD_NUM  = 
		 CAST(DATEPART(year, GETDATE()) as varchar) 
		+ RIGHT('0' + CAST(DATEPART(month, GETDATE()) as varchar), 2)
		+ RIGHT('0' + CAST(DATEPART(day, GETDATE()) as varchar), 2)
	
	
	UPDATE dbo.XX_IMAPS_TS_PREP_CONFIG_ERRORS
	SET STATUS_RECORD_NUM_REPROCESSED = @NEW_STATUS_RECORD_NUM  
	WHERE 
	STATUS_RECORD_NUM_REPROCESSED IS NULL
	AND
	NOTES IN
	(SELECT NOTES FROM IMAPS.DELTEK.TS_LN)
	
	IF @@ERROR <> 0 RAISERROR ('ERROR - UPDATE', 16, 1) 	


	
	











