ALTER TABLE dbo.XX_PCLAIM_IN_TMP ALTER COLUMN COST [decimal](9, 2) 
GO
ALTER TABLE dbo.XX_PCLAIM_IN_TMP ALTER COLUMN BILL_RATE [decimal](9, 2) 
GO
ALTER TABLE dbo.XX_PCLAIM_IN_TMP ALTER COLUMN HOURS_CHARGED [decimal](9, 2) 
GO