-- Reference FSST Service Request No. CR8954

/*
 * IMPORTANT: The DDL for table XX_PCLAIM_IN_ARCH has already been implemented or deployed on 08/30/2016 for IMAPS Help Request 20160830124307.
 */

USE IMAPSStg
GO

ALTER TABLE dbo.XX_PCLAIM_IN_ARCH ALTER COLUMN PCLAIM_IN_RECORD_NUM bigint NOT NULL
GO

ALTER TABLE dbo.XX_PCLAIM_IN_MISCODES ALTER COLUMN PCLAIM_IN_RECORD_NUM bigint NOT NULL
GO

ALTER TABLE dbo.XX_PCLAIM_IN_MISCODES_ARCH ALTER COLUMN PCLAIM_IN_RECORD_NUM bigint NOT NULL
GO
