-- Reference ClearQuest Record No. CP600000413
-- Reference BP&S Service Request No. CR1639

USE IMAPSStg
GO

ALTER TABLE dbo.XX_PCLAIM_IN_TMP ADD PAY_TYPE char(3) NOT NULL
GO

ALTER TABLE dbo.XX_PCLAIM_IN_TMP ADD VEND_COMPANY_ID char(1) NOT NULL
GO

ALTER TABLE dbo.XX_PCLAIM_IN ADD PAY_TYPE varchar(3) NULL
GO

ALTER TABLE dbo.XX_PCLAIM_IN_ARCH ADD PAY_TYPE varchar(3) NULL
GO
