if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[XX_PCLAIM_IN_LOG]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[XX_PCLAIM_IN_LOG]
GO

CREATE TABLE [dbo].[XX_PCLAIM_IN_LOG] (
	[CREATED_BY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[CREATED_DATE] [datetime] NOT NULL ,
	[TOTAL_RECORDS] [numeric](9, 0) NOT NULL ,
	[TOTAL_HOURS] [decimal](14, 2) NOT NULL ,
	[STATUS_RECORD_NUM] [int] NULL ,
	[RECORD_NUM] [int] IDENTITY (1, 1) NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[XX_PCLAIM_IN_LOG] WITH NOCHECK ADD 
	CONSTRAINT [PK_XX_PCLAIM_IN_LOG] PRIMARY KEY  CLUSTERED 
	(
		[RECORD_NUM]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [IX_XX_PCLAIM_IN_LOG] ON [dbo].[XX_PCLAIM_IN_LOG]([CREATED_BY]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[XX_PCLAIM_IN_LOG] ADD 
	CONSTRAINT [FK_XX_PCLAIM_IN_LOG_XX_IMAPS_INT_STATUS] FOREIGN KEY 
	(
		[STATUS_RECORD_NUM]
	) REFERENCES [dbo].[XX_IMAPS_INT_STATUS] (
		[STATUS_RECORD_NUM]
	)
GO

